(function(f){var g=window.AmazonUIPageJS||window.P,h=g._namespace||g.attributeErrors,e=h?h("JQueryUI_Core_AUIBuild",""):g;e.guardFatal?e.guardFatal(f)(e,window):e.execute(function(){f(e,window)})})(function(f,g,h){f.when("jQuery").register("jQueryUI-core",function(e){(function(b,e){function f(a,c){var d=a.nodeName.toLowerCase();if("area"===d){c=a.parentNode;d=c.name;if(!a.href||!d||"map"!==c.nodeName.toLowerCase())return!1;a=b("img[usemap\x3d#"+d+"]")[0];return!!a&&g(a)}return(/input|select|textarea|button|object/.test(d)?
!a.disabled:"a"===d?a.href||c:c)&&g(a)}function g(a){return b.expr.filters.visible(a)&&!b(a).parents().addBack().filter(function(){return"hidden"===b.css(this,"visibility")}).length}var h=0,k=/^ui-id-\d+$/;b.ui=b.ui||{};b.extend(b.ui,{version:"1.10.3",keyCode:{BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,
TAB:9,UP:38}});b.fn.extend({focus:function(a){return function(c,d){return"number"===typeof c?this.each(function(){var a=this;setTimeout(function(){b(a).focus();d&&d.call(a)},c)}):a.apply(this,arguments)}}(b.fn.focus),scrollParent:function(){var a=b.ui.ie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.css(this,"position"))&&/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+
b.css(this,"overflow-x"))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0);return/fixed/.test(this.css("position"))||!a.length?b(document):a},zIndex:function(a){if(a!==e)return this.css("zIndex",a);if(this.length){a=b(this[0]);for(var c;a.length&&a[0]!==document;){c=a.css("position");if("absolute"===c||"relative"===c||"fixed"===c)if(c=parseInt(a.css("zIndex"),10),!isNaN(c)&&0!==c)return c;a=a.parent()}}return 0},
uniqueId:function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++h)})},removeUniqueId:function(){return this.each(function(){k.test(this.id)&&b(this).removeAttr("id")})}});b.extend(b.expr[":"],{data:b.expr.createPseudo?b.expr.createPseudo(function(a){return function(c){return!!b.data(c,a)}}):function(a,c,d){return!!b.data(a,d[3])},focusable:function(a){return f(a,!isNaN(b.attr(a,"tabindex")))},tabbable:function(a){var c=b.attr(a,"tabindex"),d=isNaN(c);return(d||0<=c)&&f(a,!d)}});b("\x3ca\x3e").outerWidth(1).jquery||
b.each(["Width","Height"],function(a,c){function d(a,c,d,e){b.each(l,function(){c-=parseFloat(b.css(a,"padding"+this))||0;d&&(c-=parseFloat(b.css(a,"border"+this+"Width"))||0);e&&(c-=parseFloat(b.css(a,"margin"+this))||0)});return c}var l="Width"===c?["Left","Right"]:["Top","Bottom"],f=c.toLowerCase(),g={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+c]=function(a){return a===e?g["inner"+c].call(this):this.each(function(){b(this).css(f,
d(this,a)+"px")})};b.fn["outer"+c]=function(a,e){return"number"!==typeof a?g["outer"+c].call(this,a):this.each(function(){b(this).css(f,d(this,a,!0,e)+"px")})}});b.fn.addBack||(b.fn.addBack=function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))});b("\x3ca\x3e").data("a-b","a").removeData("a-b").data("a-b")&&(b.fn.removeData=function(a){return function(c){return arguments.length?a.call(this,b.camelCase(c)):a.call(this)}}(b.fn.removeData));b.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());
b.support.selectstart="onselectstart"in document.createElement("div");b.fn.extend({disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.extend(b.ui,{plugin:{add:function(a,c,d){var e;a=b.ui[a].prototype;for(e in d)a.plugins[e]=a.plugins[e]||[],a.plugins[e].push([c,d[e]])},call:function(a,b,d){var c=a.plugins[b];if(c&&a.element[0].parentNode&&
11!==a.element[0].parentNode.nodeType)for(b=0;b<c.length;b++)a.options[c[b][0]]&&c[b][1].apply(a.element,d)}},hasScroll:function(a,c){if("hidden"===b(a).css("overflow"))return!1;c=c&&"left"===c?"scrollLeft":"scrollTop";if(0<a[c])return!0;a[c]=1;var d=0<a[c];a[c]=0;return d}})})(e);return e})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,k=p?p("JQueryUI_Widget_AUIBuild",""):m;k.guardFatal?k.guardFatal(n)(k,window):k.execute(function(){n(k,window)})})(function(n,m,p){n.when("jQuery").register("jQueryUI-widget",function(k){(function(c,k){var n=0,m=Array.prototype.slice,p=c.cleanData;c.cleanData=function(b){for(var a=0,f;null!=(f=b[a]);a++)try{c(f).triggerHandler("remove")}catch(d){}p(b)};c.widget=function(b,a,f){var d,e,g,h,q={},l=b.split(".")[0];b=
b.split(".")[1];d=l+"-"+b;f||(f=a,a=c.Widget);c.expr[":"][d.toLowerCase()]=function(a){return!!c.data(a,d)};c[l]=c[l]||{};e=c[l][b];g=c[l][b]=function(a,b){if(!this._createWidget)return new g(a,b);arguments.length&&this._createWidget(a,b)};c.extend(g,e,{version:f.version,_proto:c.extend({},f),_childConstructors:[]});h=new a;h.options=c.widget.extend({},h.options);c.each(f,function(b,d){c.isFunction(d)?q[b]=function(){var c=function(){return a.prototype[b].apply(this,arguments)},f=function(c){return a.prototype[b].apply(this,
c)};return function(){var b=this._super,a=this._superApply,e;this._super=c;this._superApply=f;e=d.apply(this,arguments);this._super=b;this._superApply=a;return e}}():q[b]=d});g.prototype=c.widget.extend(h,{widgetEventPrefix:e?h.widgetEventPrefix:b},q,{constructor:g,namespace:l,widgetName:b,widgetFullName:d});e?(c.each(e._childConstructors,function(b,a){var d=a.prototype;c.widget(d.namespace+"."+d.widgetName,g,a._proto)}),delete e._childConstructors):a._childConstructors.push(g);c.widget.bridge(b,
g)};c.widget.extend=function(b){for(var a=m.call(arguments,1),f=0,d=a.length,e,g;f<d;f++)for(e in a[f])g=a[f][e],a[f].hasOwnProperty(e)&&g!==k&&(c.isPlainObject(g)?b[e]=c.isPlainObject(b[e])?c.widget.extend({},b[e],g):c.widget.extend({},g):b[e]=g);return b};c.widget.bridge=function(b,a){var f=a.prototype.widgetFullName||b;c.fn[b]=function(d){var e="string"===typeof d,g=m.call(arguments,1),h=this;d=!e&&g.length?c.widget.extend.apply(null,[d].concat(g)):d;e?this.each(function(){var a,e=c.data(this,
f);if(!e)return c.error("cannot call methods on "+b+" prior to initialization; attempted to call method '"+d+"'");if(!c.isFunction(e[d])||"_"===d.charAt(0))return c.error("no such method '"+d+"' for "+b+" widget instance");a=e[d].apply(e,g);if(a!==e&&a!==k)return h=a&&a.jquery?h.pushStack(a.get()):a,!1}):this.each(function(){var b=c.data(this,f);b?b.option(d||{})._init():c.data(this,f,new a(d,this))});return h}};c.Widget=function(){};c.Widget._childConstructors=[];c.Widget.prototype={widgetName:"widget",
widgetEventPrefix:"",defaultElement:"\x3cdiv\x3e",options:{disabled:!1,create:null},_createWidget:function(b,a){a=c(a||this.defaultElement||this)[0];this.element=c(a);this.uuid=n++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=c.widget.extend({},this.options,this._getCreateOptions(),b);this.bindings=c();this.hoverable=c();this.focusable=c();a!==this&&(c.data(a,this.widgetFullName,this),this._on(!0,this.element,{remove:function(b){b.target===a&&this.destroy()}}),this.document=c(a.style?
a.ownerDocument:a.document||a),this.window=c(this.document[0].defaultView||this.document[0].parentWindow));this._create();this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:c.noop,_getCreateEventData:c.noop,_create:c.noop,_init:c.noop,destroy:function(){this._destroy();this.element.unbind(this.eventNamespace).removeData(this.widgetName).removeData(this.widgetFullName).removeData(c.camelCase(this.widgetFullName));this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+
"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);this.hoverable.removeClass("ui-state-hover");this.focusable.removeClass("ui-state-focus")},_destroy:c.noop,widget:function(){return this.element},option:function(b,a){var f=b,d,e,g;if(0===arguments.length)return c.widget.extend({},this.options);if("string"===typeof b)if(f={},d=b.split("."),b=d.shift(),d.length){e=f[b]=c.widget.extend({},this.options[b]);for(g=0;g<d.length-1;g++)e[d[g]]=e[d[g]]||{},e=e[d[g]];b=d.pop();if(a===
k)return e[b]===k?null:e[b];e[b]=a}else{if(a===k)return this.options[b]===k?null:this.options[b];f[b]=a}this._setOptions(f);return this},_setOptions:function(b){for(var a in b)this._setOption(a,b[a]);return this},_setOption:function(b,a){this.options[b]=a;"disabled"===b&&(this.widget().toggleClass(this.widgetFullName+"-disabled ui-state-disabled",!!a).attr("aria-disabled",a),this.hoverable.removeClass("ui-state-hover"),this.focusable.removeClass("ui-state-focus"));return this},enable:function(){return this._setOption("disabled",
!1)},disable:function(){return this._setOption("disabled",!0)},_on:function(b,a,f){var d,e=this;"boolean"!==typeof b&&(f=a,a=b,b=!1);f?(a=d=c(a),this.bindings=this.bindings.add(a)):(f=a,a=this.element,d=this.widget());c.each(f,function(f,h){function k(){if(b||!0!==e.options.disabled&&!c(this).hasClass("ui-state-disabled"))return("string"===typeof h?e[h]:h).apply(e,arguments)}"string"!==typeof h&&(k.guid=h.guid=h.guid||k.guid||c.guid++);var l=f.match(/^(\w+)\s*(.*)$/),m=l[1]+e.eventNamespace;(l=l[2])?
d.delegate(l,m,k):a.bind(m,k)})},_off:function(b,a){a=(a||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;b.unbind(a).undelegate(a)},_delay:function(b,a){var c=this;return setTimeout(function(){return("string"===typeof b?c[b]:b).apply(c,arguments)},a||0)},_hoverable:function(b){this.hoverable=this.hoverable.add(b);this._on(b,{mouseenter:function(a){c(a.currentTarget).addClass("ui-state-hover")},mouseleave:function(a){c(a.currentTarget).removeClass("ui-state-hover")}})},_focusable:function(b){this.focusable=
this.focusable.add(b);this._on(b,{focusin:function(a){c(a.currentTarget).addClass("ui-state-focus")},focusout:function(a){c(a.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(b,a,f){var d,e=this.options[b];f=f||{};a=c.Event(a);a.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();a.target=this.element[0];if(b=a.originalEvent)for(d in b)d in a||(a[d]=b[d]);this.element.trigger(a,f);return!(c.isFunction(e)&&!1===e.apply(this.element[0],[a].concat(f))||a.isDefaultPrevented())}};
c.each({show:"fadeIn",hide:"fadeOut"},function(b,a){c.Widget.prototype["_"+b]=function(f,d,e){"string"===typeof d&&(d={effect:d});var g,h=d?!0===d||"number"===typeof d?a:d.effect||a:b;d=d||{};"number"===typeof d&&(d={duration:d});g=!c.isEmptyObject(d);d.complete=e;d.delay&&f.delay(d.delay);if(g&&c.effects&&c.effects.effect[h])f[b](d);else if(h!==b&&f[h])f[h](d.duration,d.easing,e);else f.queue(function(a){c(this)[b]();e&&e.call(f[0]);a()})}})})(k);return k})});
/* ******** */
(function(t){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,h=r?r("JQueryUI_Position_AUIBuild",""):p;h.guardFatal?h.guardFatal(t)(h,window):h.execute(function(){t(h,window)})})(function(t,p,r){t.when("jQuery").register("jQueryUI-position",function(h){(function(d,h){function t(a,b,c){return[parseFloat(a[0])*(y.test(a[0])?b/100:1),parseFloat(a[1])*(y.test(a[1])?c/100:1)]}function r(a){var b=a[0];return 9===b.nodeType?{width:a.width(),height:a.height(),offset:{top:0,left:0}}:
d.isWindow(b)?{width:a.width(),height:a.height(),offset:{top:a.scrollTop(),left:a.scrollLeft()}}:b.preventDefault?{width:0,height:0,offset:{top:b.pageY,left:b.pageX}}:{width:a.outerWidth(),height:a.outerHeight(),offset:a.offset()}}d.ui=d.ui||{};var u,A=Math.max,q=Math.abs,E=Math.round,z=/left|center|right/,B=/top|center|bottom/,C=/[\+\-]\d+(\.[\d]+)?%?/,F=/^\w+/,y=/%$/,G=d.fn.position;d.position={scrollbarWidth:function(){if(u!==h)return u;var a,b,c=d("\x3cdiv style\x3d'display:block;width:50px;height:50px;overflow:hidden;'\x3e\x3cdiv style\x3d'height:100px;width:auto;'\x3e\x3c/div\x3e\x3c/div\x3e");
b=c.children()[0];d("body").append(c);a=b.offsetWidth;c.css("overflow","scroll");b=b.offsetWidth;a===b&&(b=c[0].clientWidth);c.remove();return u=a-b},getScrollInfo:function(a){var b=a.isWindow?"":a.element.css("overflow-x"),c=a.isWindow?"":a.element.css("overflow-y"),b="scroll"===b||"auto"===b&&a.width<a.element[0].scrollWidth;return{width:"scroll"===c||"auto"===c&&a.height<a.element[0].scrollHeight?d.position.scrollbarWidth():0,height:b?d.position.scrollbarWidth():0}},getWithinInfo:function(a){a=
d(a||p);var b=d.isWindow(a[0]);return{element:a,isWindow:b,offset:a.offset()||{left:0,top:0},scrollLeft:a.scrollLeft(),scrollTop:a.scrollTop(),width:b?a.width():a.outerWidth(),height:b?a.height():a.outerHeight()}}};d.fn.position=function(a){if(!a||!a.of)return G.apply(this,arguments);a=d.extend({},a);var b,c,g,n,f,e,h=d(a.of),m=d.position.getWithinInfo(a.within),l=d.position.getScrollInfo(m),p=(a.collision||"flip").split(" "),u={};e=r(h);h[0].preventDefault&&(a.at="left top");c=e.width;g=e.height;
n=e.offset;f=d.extend({},n);d.each(["my","at"],function(){var b=(a[this]||"").split(" "),c,g;1===b.length&&(b=z.test(b[0])?b.concat(["center"]):B.test(b[0])?["center"].concat(b):["center","center"]);b[0]=z.test(b[0])?b[0]:"center";b[1]=B.test(b[1])?b[1]:"center";c=C.exec(b[0]);g=C.exec(b[1]);u[this]=[c?c[0]:0,g?g[0]:0];a[this]=[F.exec(b[0])[0],F.exec(b[1])[0]]});1===p.length&&(p[1]=p[0]);"right"===a.at[0]?f.left+=c:"center"===a.at[0]&&(f.left+=c/2);"bottom"===a.at[1]?f.top+=g:"center"===a.at[1]&&
(f.top+=g/2);b=t(u.at,c,g);f.left+=b[0];f.top+=b[1];return this.each(function(){var e,r,v=d(this),w=v.outerWidth(),x=v.outerHeight(),y=parseInt(d.css(this,"marginLeft"),10)||0,z=parseInt(d.css(this,"marginTop"),10)||0,B=w+y+(parseInt(d.css(this,"marginRight"),10)||0)+l.width,C=x+z+(parseInt(d.css(this,"marginBottom"),10)||0)+l.height,k=d.extend({},f),D=t(u.my,v.outerWidth(),v.outerHeight());"right"===a.my[0]?k.left-=w:"center"===a.my[0]&&(k.left-=w/2);"bottom"===a.my[1]?k.top-=x:"center"===a.my[1]&&
(k.top-=x/2);k.left+=D[0];k.top+=D[1];d.support.offsetFractions||(k.left=E(k.left),k.top=E(k.top));e={marginLeft:y,marginTop:z};d.each(["left","top"],function(f,n){if(d.ui.position[p[f]])d.ui.position[p[f]][n](k,{targetWidth:c,targetHeight:g,elemWidth:w,elemHeight:x,collisionPosition:e,collisionWidth:B,collisionHeight:C,offset:[b[0]+D[0],b[1]+D[1]],my:a.my,at:a.at,within:m,elem:v})});a.using&&(r=function(b){var d=n.left-k.left,e=d+c-w,f=n.top-k.top,m=f+g-x,l={target:{element:h,left:n.left,top:n.top,
width:c,height:g},element:{element:v,left:k.left,top:k.top,width:w,height:x},horizontal:0>e?"left":0<d?"right":"center",vertical:0>m?"top":0<f?"bottom":"middle"};c<w&&q(d+e)<c&&(l.horizontal="center");g<x&&q(f+m)<g&&(l.vertical="middle");A(q(d),q(e))>A(q(f),q(m))?l.important="horizontal":l.important="vertical";a.using.call(this,b,l)});v.offset(d.extend(k,{using:r}))})};d.ui.position={fit:{left:function(a,b){var c=b.within,g=c.isWindow?c.scrollLeft:c.offset.left,d=c.width,f=a.left-b.collisionPosition.marginLeft,
c=g-f,e=f+b.collisionWidth-d-g;b.collisionWidth>d?0<c&&0>=e?(g=a.left+c+b.collisionWidth-d-g,a.left+=c-g):a.left=0<e&&0>=c?g:c>e?g+d-b.collisionWidth:g:a.left=0<c?a.left+c:0<e?a.left-e:A(a.left-f,a.left)},top:function(a,b){var c=b.within,g=c.isWindow?c.scrollTop:c.offset.top,d=b.within.height,f=a.top-b.collisionPosition.marginTop,c=g-f,e=f+b.collisionHeight-d-g;b.collisionHeight>d?0<c&&0>=e?(g=a.top+c+b.collisionHeight-d-g,a.top+=c-g):a.top=0<e&&0>=c?g:c>e?g+d-b.collisionHeight:g:a.top=0<c?a.top+
c:0<e?a.top-e:A(a.top-f,a.top)}},flip:{left:function(a,b){var c=b.within,d=c.offset.left+c.scrollLeft,n=c.width,f=c.isWindow?c.scrollLeft:c.offset.left,e=a.left-b.collisionPosition.marginLeft,c=e-f,h=e+b.collisionWidth-n-f,e="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,m="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,l=-2*b.offset[0];if(0>c){if(d=a.left+e+m+l+b.collisionWidth-n-d,0>d||d<q(c))a.left+=e+m+l}else 0<h&&(d=a.left-b.collisionPosition.marginLeft+e+m+l-
f,0<d||q(d)<h)&&(a.left+=e+m+l)},top:function(a,b){var c=b.within,d=c.offset.top+c.scrollTop,n=c.height,f=c.isWindow?c.scrollTop:c.offset.top,e=a.top-b.collisionPosition.marginTop,c=e-f,h=e+b.collisionHeight-n-f,e="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,m="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,l=-2*b.offset[1];0>c?(d=a.top+e+m+l+b.collisionHeight-n-d,a.top+e+m+l>c&&(0>d||d<q(c))&&(a.top+=e+m+l)):0<h&&(d=a.top-b.collisionPosition.marginTop+e+m+l-
f,a.top+e+m+l>h&&(0<d||q(d)<h)&&(a.top+=e+m+l))}},flipfit:{left:function(){d.ui.position.flip.left.apply(this,arguments);d.ui.position.fit.left.apply(this,arguments)},top:function(){d.ui.position.flip.top.apply(this,arguments);d.ui.position.fit.top.apply(this,arguments)}}};(function(){var a,b,c,g,h=document.getElementsByTagName("body")[0];c=document.createElement("div");a=document.createElement(h?"div":"body");b={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};h&&d.extend(b,
{position:"absolute",left:"-1000px",top:"-1000px"});for(g in b)a.style[g]=b[g];a.appendChild(c);b=h||document.documentElement;b.insertBefore(a,b.firstChild);c.style.cssText="position: absolute; left: 10.7432222px;";c=d(c).offset().left;d.support.offsetFractions=10<c&&11>c;a.innerHTML="";b.removeChild(a)})()})(h);return h})});
/* ******** */
(function(g){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,f=k?k("JQueryUI_Menu_AUIBuild",""):h;f.guardFatal?f.guardFatal(g)(f,window):f.execute(function(){g(f,window)})})(function(g,h,k){g.when("jQueryUI-core","jQueryUI-position","jQueryUI-widget").register("jQueryUI-menu",function(f){(function(d,f){d.widget("ui.menu",{version:"1.10.3",defaultElement:"\x3cul\x3e",delay:300,options:{icons:{submenu:"ui-icon-carat-1-e"},menus:"ul",position:{my:"left top",at:"right top"},role:"menu",
blur:null,focus:null,select:null},_create:function(){this.activeMenu=this.element;this.mouseHandled=!1;this.element.uniqueId().addClass("ui-menu ui-widget ui-widget-content ui-corner-all").toggleClass("ui-menu-icons",!!this.element.find(".ui-icon").length).attr({role:this.options.role,tabIndex:0}).bind("click"+this.eventNamespace,d.proxy(function(a){this.options.disabled&&a.preventDefault()},this));this.options.disabled&&this.element.addClass("ui-state-disabled").attr("aria-disabled","true");this._on({"mousedown .ui-menu-item \x3e a":function(a){a.preventDefault()},
"click .ui-state-disabled \x3e a":function(a){a.preventDefault()},"click .ui-menu-item:has(a)":function(a){var b=d(a.target).closest(".ui-menu-item");!this.mouseHandled&&b.not(".ui-state-disabled").length&&(this.mouseHandled=!0,this.select(a),b.has(".ui-menu").length?this.expand(a):this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.active&&1===this.active.parents(".ui-menu").length&&clearTimeout(this.timer)))},"mouseenter .ui-menu-item":function(a){var b=d(a.currentTarget);b.siblings().children(".ui-state-active").removeClass("ui-state-active");
this.focus(a,b)},mouseleave:"collapseAll","mouseleave .ui-menu":"collapseAll",focus:function(a,b){var c=this.active||this.element.children(".ui-menu-item").eq(0);b||this.focus(a,c)},blur:function(a){this._delay(function(){d.contains(this.element[0],this.document[0].activeElement)||this.collapseAll(a)})},keydown:"_keydown"});this.refresh();this._on(this.document,{click:function(a){d(a.target).closest(".ui-menu").length||this.collapseAll(a);this.mouseHandled=!1}})},_destroy:function(){this.element.removeAttr("aria-activedescendant").find(".ui-menu").addBack().removeClass("ui-menu ui-widget ui-widget-content ui-corner-all ui-menu-icons").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".ui-menu-item").removeClass("ui-menu-item").removeAttr("role").removeAttr("aria-disabled").children("a").removeUniqueId().removeClass("ui-corner-all ui-state-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=d(this);a.data("ui-menu-submenu-carat")&&a.remove()});this.element.find(".ui-menu-divider").removeClass("ui-menu-divider ui-widget-content")},_keydown:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,
"\\$\x26")}var c,e,f,g,h=!0;switch(a.keyCode){case d.ui.keyCode.PAGE_UP:this.previousPage(a);break;case d.ui.keyCode.PAGE_DOWN:this.nextPage(a);break;case d.ui.keyCode.HOME:this._move("first","first",a);break;case d.ui.keyCode.END:this._move("last","last",a);break;case d.ui.keyCode.UP:this.previous(a);break;case d.ui.keyCode.DOWN:this.next(a);break;case d.ui.keyCode.LEFT:this.collapse(a);break;case d.ui.keyCode.RIGHT:this.active&&!this.active.is(".ui-state-disabled")&&this.expand(a);break;case d.ui.keyCode.ENTER:case d.ui.keyCode.SPACE:this._activate(a);
break;case d.ui.keyCode.ESCAPE:this.collapse(a);break;default:h=!1,c=this.previousFilter||"",e=String.fromCharCode(a.keyCode),f=!1,clearTimeout(this.filterTimer),e===c?f=!0:e=c+e,g=new RegExp("^"+b(e),"i"),c=this.activeMenu.children(".ui-menu-item").filter(function(){return g.test(d(this).children("a").text())}),c=f&&-1!==c.index(this.active.next())?this.active.nextAll(".ui-menu-item"):c,c.length||(e=String.fromCharCode(a.keyCode),g=new RegExp("^"+b(e),"i"),c=this.activeMenu.children(".ui-menu-item").filter(function(){return g.test(d(this).children("a").text())})),
c.length?(this.focus(a,c),1<c.length?(this.previousFilter=e,this.filterTimer=this._delay(function(){delete this.previousFilter},1E3)):delete this.previousFilter):delete this.previousFilter}h&&a.preventDefault()},_activate:function(a){this.active.is(".ui-state-disabled")||(this.active.children("a[aria-haspopup\x3d'true']").length?this.expand(a):this.select(a))},refresh:function(){var a,b=this.options.icons.submenu;a=this.element.find(this.options.menus);a.filter(":not(.ui-menu)").addClass("ui-menu ui-widget ui-widget-content ui-corner-all").hide().attr({role:this.options.role,
"aria-hidden":"true","aria-expanded":"false"}).each(function(){var a=d(this),e=a.prev("a"),f=d("\x3cspan\x3e").addClass("ui-menu-icon ui-icon "+b).data("ui-menu-submenu-carat",!0);e.attr("aria-haspopup","true").prepend(f);a.attr("aria-labelledby",e.attr("id"))});a=a.add(this.element);a.children(":not(.ui-menu-item):has(a)").addClass("ui-menu-item").attr("role","presentation").children("a").uniqueId().addClass("ui-corner-all").attr({tabIndex:-1,role:this._itemRole()});a.children(":not(.ui-menu-item)").each(function(){var a=
d(this);/[^\-\u2014\u2013\s]/.test(a.text())||a.addClass("ui-widget-content ui-menu-divider")});a.children(".ui-state-disabled").attr("aria-disabled","true");this.active&&!d.contains(this.element[0],this.active[0])&&this.blur()},_itemRole:function(){return{menu:"menuitem",listbox:"option"}[this.options.role]},_setOption:function(a,b){"icons"===a&&this.element.find(".ui-menu-icon").removeClass(this.options.icons.submenu).addClass(b.submenu);this._super(a,b)},focus:function(a,b){var c;this.blur(a,a&&
"focus"===a.type);this._scrollIntoView(b);this.active=b.first();c=this.active.children("a").addClass("ui-state-focus");this.options.role&&this.element.attr("aria-activedescendant",c.attr("id"));this.active.parent().closest(".ui-menu-item").children("a:first").addClass("ui-state-active");a&&"keydown"===a.type?this._close():this.timer=this._delay(function(){this._close()},this.delay);c=b.children(".ui-menu");c.length&&/^mouse/.test(a.type)&&this._startOpening(c);this.activeMenu=b.parent();this._trigger("focus",
a,{item:b})},_scrollIntoView:function(a){var b,c,e;this._hasScroll()&&(b=parseFloat(d.css(this.activeMenu[0],"borderTopWidth"))||0,c=parseFloat(d.css(this.activeMenu[0],"paddingTop"))||0,b=a.offset().top-this.activeMenu.offset().top-b-c,c=this.activeMenu.scrollTop(),e=this.activeMenu.height(),a=a.height(),0>b?this.activeMenu.scrollTop(c+b):b+a>e&&this.activeMenu.scrollTop(c+b-e+a))},blur:function(a,b){b||clearTimeout(this.timer);this.active&&(this.active.children("a").removeClass("ui-state-focus"),
this.active=null,this._trigger("blur",a,{item:this.active}))},_startOpening:function(a){clearTimeout(this.timer);"true"===a.attr("aria-hidden")&&(this.timer=this._delay(function(){this._close();this._open(a)},this.delay))},_open:function(a){var b=d.extend({of:this.active},this.options.position);clearTimeout(this.timer);this.element.find(".ui-menu").not(a.parents(".ui-menu")).hide().attr("aria-hidden","true");a.show().removeAttr("aria-hidden").attr("aria-expanded","true").position(b)},collapseAll:function(a,
b){clearTimeout(this.timer);this.timer=this._delay(function(){var c=b?this.element:d(a&&a.target).closest(this.element.find(".ui-menu"));c.length||(c=this.element);this._close(c);this.blur(a);this.activeMenu=c},this.delay)},_close:function(a){a||(a=this.active?this.active.parent():this.element);a.find(".ui-menu").hide().attr("aria-hidden","true").attr("aria-expanded","false").end().find("a.ui-state-active").removeClass("ui-state-active")},collapse:function(a){var b=this.active&&this.active.parent().closest(".ui-menu-item",
this.element);b&&b.length&&(this._close(),this.focus(a,b))},expand:function(a){var b=this.active&&this.active.children(".ui-menu ").children(".ui-menu-item").first();b&&b.length&&(this._open(b.parent()),this._delay(function(){this.focus(a,b)}))},next:function(a){this._move("next","first",a)},previous:function(a){this._move("prev","last",a)},isFirstItem:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},isLastItem:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length},
_move:function(a,b,c){var d;this.active&&(d="first"===a||"last"===a?this.active["first"===a?"prevAll":"nextAll"](".ui-menu-item").eq(-1):this.active[a+"All"](".ui-menu-item").eq(0));d&&d.length&&this.active||(d=this.activeMenu.children(".ui-menu-item")[b]());this.focus(c,d)},nextPage:function(a){var b,c,e;this.active?this.isLastItem()||(this._hasScroll()?(c=this.active.offset().top,e=this.element.height(),this.active.nextAll(".ui-menu-item").each(function(){b=d(this);return 0>b.offset().top-c-e}),
this.focus(a,b)):this.focus(a,this.activeMenu.children(".ui-menu-item")[this.active?"last":"first"]())):this.next(a)},previousPage:function(a){var b,c,e;this.active?this.isFirstItem()||(this._hasScroll()?(c=this.active.offset().top,e=this.element.height(),this.active.prevAll(".ui-menu-item").each(function(){b=d(this);return 0<b.offset().top-c+e}),this.focus(a,b)):this.focus(a,this.activeMenu.children(".ui-menu-item").first())):this.next(a)},_hasScroll:function(){return this.element.outerHeight()<
this.element.prop("scrollHeight")},select:function(a){this.active=this.active||d(a.target).closest(".ui-menu-item");var b={item:this.active};this.active.has(".ui-menu").length||this.collapseAll(a,!0);this._trigger("select",a,b)}})})(f)})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,m=l._namespace||l.attributeErrors,g=m?m("JQueryUI_Autocomplete_AUIBuild",""):l;g.guardFatal?g.guardFatal(h)(g,window):g.execute(function(){h(g,window)})})(function(h,l,m){h.when("jQueryUI-core","jQueryUI-position","jQueryUI-widget","jQueryUI-menu").register("jQueryUI-autocomplete",function(g){(function(c,g){var h=0;c.widget("ui.autocomplete",{version:"1.10.3",defaultElement:"\x3cinput\x3e",options:{appendTo:null,autoFocus:!1,delay:300,minLength:1,
position:{my:"left top",at:"left bottom",collision:"none"},source:null,change:null,close:null,focus:null,open:null,response:null,search:null,select:null},pending:0,_create:function(){var a,b,f,k=this.element[0].nodeName.toLowerCase(),n="textarea"===k;k="input"===k;this.isMultiLine=n?!0:k?!1:this.element.prop("isContentEditable");this.valueMethod=this.element[n||k?"val":"text"];this.isNewMenu=!0;this.element.addClass("ui-autocomplete-input").attr("autocomplete","off");this._on(this.element,{keydown:function(d){if(this.element.prop("readOnly"))b=
f=a=!0;else{b=f=a=!1;var e=c.ui.keyCode;switch(d.keyCode){case e.PAGE_UP:a=!0;this._move("previousPage",d);break;case e.PAGE_DOWN:a=!0;this._move("nextPage",d);break;case e.UP:a=!0;this._keyEvent("previous",d);break;case e.DOWN:a=!0;this._keyEvent("next",d);break;case e.ENTER:case e.NUMPAD_ENTER:this.menu.active&&(a=!0,d.preventDefault(),this.menu.select(d));break;case e.TAB:this.menu.active&&this.menu.select(d);break;case e.ESCAPE:this.menu.element.is(":visible")&&(this._value(this.term),this.close(d),
d.preventDefault());break;default:b=!0,this._searchTimeout(d)}}},keypress:function(d){if(a)a=!1,this.isMultiLine&&!this.menu.element.is(":visible")||d.preventDefault();else if(!b){var e=c.ui.keyCode;switch(d.keyCode){case e.PAGE_UP:this._move("previousPage",d);break;case e.PAGE_DOWN:this._move("nextPage",d);break;case e.UP:this._keyEvent("previous",d);break;case e.DOWN:this._keyEvent("next",d)}}},input:function(a){f?(f=!1,a.preventDefault()):this._searchTimeout(a)},focus:function(){this.selectedItem=
null;this.previous=this._value()},blur:function(a){this.cancelBlur?delete this.cancelBlur:(clearTimeout(this.searching),this.close(a),this._change(a))}});this._initSource();this.menu=c("\x3cul\x3e").addClass("ui-autocomplete ui-front").appendTo(this._appendTo()).menu({role:null}).hide().data("ui-menu");this._on(this.menu.element,{mousedown:function(a){a.preventDefault();this.cancelBlur=!0;this._delay(function(){delete this.cancelBlur});var b=this.menu.element[0];c(a.target).closest(".ui-menu-item").length||
this._delay(function(){var a=this;this.document.one("mousedown",function(d){d.target===a.element[0]||d.target===b||c.contains(b,d.target)||a.close()})})},menufocus:function(a,b){if(this.isNewMenu&&(this.isNewMenu=!1,a.originalEvent&&/^mouse/.test(a.originalEvent.type))){this.menu.blur();this.document.one("mousemove",function(){c(a.target).trigger(a.originalEvent)});return}b=b.item.data("ui-autocomplete-item");!1!==this._trigger("focus",a,{item:b})?a.originalEvent&&/^key/.test(a.originalEvent.type)&&
this._value(b.value):this.liveRegion.text(b.value)},menuselect:function(a,b){var c=b.item.data("ui-autocomplete-item"),d=this.previous;this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.previous=d,this._delay(function(){this.previous=d;this.selectedItem=c}));!1!==this._trigger("select",a,{item:c})&&this._value(c.value);this.term=this._value();this.close(a);this.selectedItem=c}});this.liveRegion=c("\x3cspan\x3e",{role:"status","aria-live":"polite"}).addClass("ui-helper-hidden-accessible").insertBefore(this.element);
this._on(this.window,{beforeunload:function(){this.element.removeAttr("autocomplete")}})},_destroy:function(){clearTimeout(this.searching);this.element.removeClass("ui-autocomplete-input").removeAttr("autocomplete");this.menu.element.remove();this.liveRegion.remove()},_setOption:function(a,b){this._super(a,b);"source"===a&&this._initSource();"appendTo"===a&&this.menu.element.appendTo(this._appendTo());"disabled"===a&&b&&this.xhr&&this.xhr.abort()},_appendTo:function(){var a=this.options.appendTo;
a&&(a=a.jquery||a.nodeType?c(a):this.document.find(a).eq(0));a||(a=this.element.closest(".ui-front"));a.length||(a=this.document[0].body);return a},_initSource:function(){var a=this;if(c.isArray(this.options.source)){var b=this.options.source;this.source=function(a,f){f(c.ui.autocomplete.filter(b,a.term))}}else if("string"===typeof this.options.source){var f=this.options.source;this.source=function(b,g){a.xhr&&a.xhr.abort();a.xhr=c.ajax({url:f,data:b,dataType:"json",success:function(a){g(a)},error:function(){g([])}})}}else this.source=
this.options.source},_searchTimeout:function(a){clearTimeout(this.searching);this.searching=this._delay(function(){this.term!==this._value()&&(this.selectedItem=null,this.search(null,a))},this.options.delay)},search:function(a,b){a=null!=a?a:this._value();this.term=this._value();if(a.length<this.options.minLength)return this.close(b);if(!1!==this._trigger("search",b))return this._search(a)},_search:function(a){this.pending++;this.element.addClass("ui-autocomplete-loading");this.cancelSearch=!1;this.source({term:a},
this._response())},_response:function(){var a=this,b=++h;return function(c){b===h&&a.__response(c);a.pending--;a.pending||a.element.removeClass("ui-autocomplete-loading")}},__response:function(a){a&&(a=this._normalize(a));this._trigger("response",null,{content:a});!this.options.disabled&&a&&a.length&&!this.cancelSearch?(this._suggest(a),this._trigger("open")):this._close()},close:function(a){this.cancelSearch=!0;this._close(a)},_close:function(a){this.menu.element.is(":visible")&&(this.menu.element.hide(),
this.menu.blur(),this.isNewMenu=!0,this._trigger("close",a))},_change:function(a){this.previous!==this._value()&&this._trigger("change",a,{item:this.selectedItem})},_normalize:function(a){return a.length&&a[0].label&&a[0].value?a:c.map(a,function(a){return"string"===typeof a?{label:a,value:a}:c.extend({label:a.label||a.value,value:a.value||a.label},a)})},_suggest:function(a){var b=this.menu.element.empty();this._renderMenu(b,a);this.isNewMenu=!0;this.menu.refresh();b.show();this._resizeMenu();b.position(c.extend({of:this.element},
this.options.position));this.options.autoFocus&&this.menu.next()},_resizeMenu:function(){var a=this.menu.element;a.outerWidth(Math.max(a.width("").outerWidth()+1,this.element.outerWidth()))},_renderMenu:function(a,b){var f=this;c.each(b,function(b,c){f._renderItemData(a,c)})},_renderItemData:function(a,b){return this._renderItem(a,b).data("ui-autocomplete-item",b)},_renderItem:function(a,b){return c("\x3cli\x3e").append(c("\x3ca\x3e").text(b.label)).appendTo(a)},_move:function(a,b){if(this.menu.element.is(":visible"))if(this.menu.isFirstItem()&&
/^previous/.test(a)||this.menu.isLastItem()&&/^next/.test(a))this._value(this.term),this.menu.blur();else this.menu[a](b);else this.search(null,b)},widget:function(){return this.menu.element},_value:function(){return this.valueMethod.apply(this.element,arguments)},_keyEvent:function(a,b){if(!this.isMultiLine||this.menu.element.is(":visible"))this._move(a,b),b.preventDefault()}});c.extend(c.ui.autocomplete,{escapeRegex:function(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")},filter:function(a,
b){var f=new RegExp(c.ui.autocomplete.escapeRegex(b),"i");return c.grep(a,function(a){return f.test(a.label||a.value||a)})}});c.widget("ui.autocomplete",c.ui.autocomplete,{options:{messages:{noResults:"No search results.",results:function(a){return a+(1<a?" results are":" result is")+" available, use up and down arrow keys to navigate."}}},__response:function(a){this._superApply(arguments);if(!this.options.disabled&&!this.cancelSearch){var b=a&&a.length?this.options.messages.results(a.length):this.options.messages.noResults;
this.liveRegion.text(b)}}})})(g)})});
/* ******** */
(function(k){var l=window.AmazonUIPageJS||window.P,x=l._namespace||l.attributeErrors,b=x?x("AuthenticationPortalAssets",""):l;b.guardFatal?b.guardFatal(k)(b,window):b.execute(function(){k(b,window)})})(function(k,l,x){k.when("A","a-modal","ready").register("ap-3p-account-connected-modal",function(b,a){var e=b.$;(b=b.state("ap-3p-account-connected-modal"))&&b.thirdPartyAccountStatus&&"rejectWithLoginIdIfConnected"===b.thirdPartyAccountStatus&&(e=e("#ap-3p-account-connected-modal-action"),(a=a.get(e))&&
a.show())});"use strict";k.when("A","AuthToolkit","client-side-counters-util","ready").register("auth-3p-phone-verification",function(b,a,e){function c(a){m&&e.incrementCounter(a)}function d(){l.NativeUI&&"function"===typeof l.NativeUI.applyFullFlash&&l.setTimeout(function(){l.NativeUI.applyFullFlash()},900)}var f=b.$,g=f("#auth-pv-enter-code");try{var m=/HUAWEI|HONOR/.test(navigator.userAgent.toUpperCase())}catch(h){m=!1}c("auth:module-entered");a.countingDown("#ap-3p-get-pin-code-button");b.on("AuthToolkit.countDownEnd",
function(a){"#ap-3p-get-pin-code-button"===a&&(f("#auth-phone-number").removeClass("a-form-disabled"),f("#auth-phone-number-wrapper").removeClass("a-form-disabled"),f("#auth-phone-number").attr("disabled",!1))});b.on("a:dropdown:auth-country-picker:select",d);g.bind("change paste keyup",function(){0<f(this).val().length?a.enableButton("#ap-3p-pv-create-account"):a.disableButton("#ap-3p-pv-create-account")});b.declarative("auth-verify-button-declarative","click touchstart",function(){c("auth:pin-input-handler");
var a=f("#auth-3p-pv-form");a.find("#insisted").val("false");a.find("#getPinCodeAction").val("true");a.submit();e.incrementCounter("Click3PCodeVerifyButton");c("auth:pin-input-handler-huawei-submitted");c("auth:pin-input-handler#insisted"+a.find("#insisted").val());c("auth:pin-input-handler#getPinCodeAction"+a.find("#getPinCodeAction").val())});f("#ap-3p-insist-verify-link").click(function(){var a=f("#auth-3p-pv-form");a.find("#auth-country-picker").val(f("#ap-3p-insist-verify-link").attr("countrycode"));
a.find("#auth-phone-number").val(f("#ap-3p-insist-verify-link").attr("phonenumber"));a.find("#insisted").val("true");a.submit()});return{callApplyFullFlash:d}});k.when("A","a-modal","ready").register("ap-3p-pv-modal",function(b,a){var e=b.$,c=b.state("ap-3p-pv-modal");if(c){var d=c.thirdPartyPhoneConflict;if(d&&"None"!==d.toString()){var f=e("#"+c.formIdToBindTo);e=e("#ap-3p-pv-modal-action");(a=a.get(e))&&d&&"None"!==d.toString()&&a.show();b.declarative("ap-3p-pv-modal-complete","click",function(){d&&
"WeChat"===d.toString()&&(f.find("#insisted").val("true"),f.submit())})}}});"use strict";k.when("A","ready").register("account_conflict_continue_verify",function(b){var a=b.$;a("#auth-account-conflict-continue-verify-url").click(function(b){b.preventDefault();b=a("#ap_account_conflict_warning_customer_actions");b.exists()&&b.submit()});a.fn.exists=function(){return 0!==this.length}});"use strict";k.when("A","cvf","ready").register("auth-account-switcher",function(b,a){function e(a){return x}function c(a){l.location=
d(l.location);return x}function d(a){var b=a.search;return b?b.match(f)?a.href.replace(f,"$1ACCOUNT_SWITCH_FAILED"):a.href+"\x26errorCodes\x3dACCOUNT_SWITCH_FAILED":a.href+"?errorCodes\x3dACCOUNT_SWITCH_FAILED"}b=b.$;var f=/(errorCodes=)[\w\d]+/g;b("#ap-account-switcher-container").length&&"undefined"!==typeof b("#ap-account-switcher-container").attr("data-token")&&(b={target:b("#ap-account-switcher-container"),requestToken:b("#ap-account-switcher-container").attr("data-token"),requestArbToken:b("#ap-account-switcher-container").attr("data-arbToken"),
onSuccess:e,onError:c,autoStart:!1,widgetMetricsScope:"CvfAccountSwitcherClientSideMetrics"},a.create(b).start());return{getUrlWithSwitchErrorCodeAdded:d}});"use strict";k.register("AmazonHelpPopup",function(){return function(b,a,e){l.open(b,a,e).focus();return!1}});"use strict";k.when("A","client-side-counters-util","counters-name","ready").register("apple-login-button-counter",function(b,a,e){var c=e.getCommonCounterNamePrefix()+":APPLE";b=b.$("#signInWithAppleSubmit");0<b.length&&b.click(function(){a.incrementCounter(c)});
return{appleButtonClickEventCounterName:c}});"use strict";k.when("A","auth-image-captcha","ready").register("auth-audio-captcha-handler",function(b,a){function e(a){a&&a.captchaImageUrl&&t.test(a.captchaImageUrl)?(g.val(a.cesString),r.attr("src",a.captchaImageUrl),f.load()):(k.log("Failed to load new CAPTCHA due to invalid response from server","FATAL","auth-audio-captcha-handler"),l.location.reload(!0))}function c(){b.ajax(r.attr("data-refresh-url"),C);D.focus()}var d=b.$,f=d("#audio-captcha")[0],
g=d("input[type\x3d'hidden'][name\x3d'ces']"),m=d("#audio-captcha-section"),h=d("#auth-captcha-guess"),u=d("#image-captcha-section"),r=d("#mp3-file"),q=d("#auth-switch-captcha-to-audio-container"),n=d("#use_audio_captcha"),y=d("#use_image_captcha");d("#auth-error-message-box");var t=/^(http|https):\/\//,w=d(".a-mobile").length,D=d("#audio-captcha-play-pause-button"),z=d("#audio-captcha-options"),A=d("#image-captcha-options"),p=d("#image-captcha-placeholder"),B=d("#audio-captcha-placeholder"),C={cache:!1,
timeout:1E3,error:function(){k.log("Failed to refresh CAPTCHA due to error response from server","FATAL","auth-audio-captcha-handler");l.location.reload(!0)},success:e};b.capabilities.audio&&q.show();return{switchCaptchaToAudio:function(){u.hide();y.val("false");m.show();n.val("true");h.val("");c();w&&(A.hide(),z.show(),h.attr("placeholder",B.val()))},switchCaptchaToImage:function(){m.hide();n.val("false");u.show();y.val("true");h.val("");f.pause();a.refresh();h.focus();w&&(A.show(),z.hide(),h.attr("placeholder",
p.val()))},audioRefresh:c,audioPlayButton:function(){f.paused?(h.focus(),f.play()):f.pause()},handleSuccess:e}});"use strict";k.when("A","auth-audio-captcha-handler","ready").register("auth-audio-captcha",function(b,a){b=b.$;b("#auth-switch-captcha-to-audio").click(function(b){b.preventDefault();a.switchCaptchaToAudio()});b("#auth-switch-captcha-to-image").click(function(b){b.preventDefault();a.switchCaptchaToImage()});b("#auth-refresh-audio").click(function(b){b.preventDefault();a.audioRefresh()});
b("#audio-captcha-play-pause-button").click(function(b){b.preventDefault();a.audioPlayButton()});return{handleSuccess:a.handleSuccess}});"use strict";k.when("A","client-side-counters-util","ready").register("autocomplete-signup-metric",function(b,a){var e=b.$;e("#ap_customer_name, #ap_email, #ap_phone_number").bind("animationstart",function(b){"onAutoFillChanged"===b.originalEvent.animationName&&(e(this).hasClass("auth-required-field")?a.incrementCounter("AutocompleteSignupChangedCounterRequired:"+
this.id):a.incrementCounter("AutocompleteSignupChangedCounterOptional:"+this.id))})});"use strict";k.when("A","ready").execute(function(b){b.$(".auth-autofocus").first().focus()});"use strict";k.when("A","ready").execute(function(b){function a(){location.href=c.returnToAddress}function e(){clearTimeout(d);d=setTimeout(a,f)}var c=b.state("timeout-parameters");if(c){var d=0,f=c.timeoutValue;document.onmousemove=e;document.onkeypress=e;document.ontouchstart=e;document.ontouchmove=e;document.ontouchend=
e;e()}});"use strict";k.when("A","client-side-counters-util","ready").execute(function(b,a){b.on("a:expander:blacklist_password_learn_more:toggle:expand",function(b){a.incrementCounter("BlacklistPasswordInstructionLearnMoreExpand")});b.on("a:expander:blacklist_password_learn_more:toggle:collapse",function(b){a.incrementCounter("BlacklistPasswordInstructionLearnMoreCollapse")})});"use strict";k.when("page-util").register("client-side-counters-util",function(b){function a(a,b){var c=l.ue;c&&"function"===
typeof c.count&&(b||(b=(c.count(a)||0)+1),c.count(a,b))}return{incrementCounter:function(b){a(b)},insertCounter:a,triggerWeblab:function(a,b){var c=l.ue;c&&"function"===typeof c.trigger&&c.trigger(a,b)},getCounterNameWithDeviceAndPageType:function(a){return a+b.determineDeviceType()+b.determinePageType()}}});"use strict";k.when("A","AuthToolkit","auth-pv-resend-utility","ready").register("auth-cnep-add-password",function(b,a,e){var c=b.$;if(!(1>c("#ap-cnep-add-password-resend-code-button").length)){a.countingDown("#ap-cnep-add-password-resend-code-button");
var d=b.state("auth-cnep-add-password-resend-state");if(d){var f=c("#auth-cnep-add-password-client-side-success-box"),g=c(".auth-pv-client-side-success-messages li"),m=c("#auth-cnep-add-password-client-side-error-box"),h=c(".auth-pv-client-side-error-messages li"),u=c(".auth-server-side-message-box"),k=c("#auth-resend-code-succeeded"),q=c("#auth-there-was-an-error-throttled"),n=c("#auth-there-was-an-error");d.sessionTimeoutUrl=d.cnepUrl;var y=function(){e.successHandler(k,f)},t=function(a){e.errorHandler(a,
d,q,n,m,!1)};c("#ap-cnep-add-password-resend-code-button").click(function(){"#ap-cnep-add-password-resend-code-button".isDisabled||(e.hideMessageBox(f,g,m,h,u),b.ajax(d.resendPinCodeUrl,{method:"post",success:y,error:t}),"undefined"===typeof c("#ap-cnep-add-password-resend-code-button")||c("#ap-cnep-add-password-resend-code-button").hasClass("a-button-disabled")||(c("#ap-cnep-add-password-resend-code-button").addClass("a-button-disabled"),c("#ap-cnep-add-password-resend-code-button").find(".a-button-text").attr("disabled",
"disabled")),c("#ap-cnep-add-password-resend-code-button").find(".a-button-text").data("remaining",d.originalRemaining),a.countingDown("#ap-cnep-add-password-resend-code-button"))})}}});"use strict";k.when("A","client-side-counters-util","ready").register("auth-cnep-authenticator-metrics",function(b,a){var e=b.$,c=Object.freeze({CLICK_ADD_AUTHENTICATOR:"CNEPClickAddAuthenticator",CLICK_EDIT_AUTHENTICATOR:"CNEPClickEditAuthenticator"});(function(){1===e("input#auth-cnep-authenticator-add-button").length&&
e("input#auth-cnep-authenticator-add-button").click(function(){a.incrementCounter(c.CLICK_ADD_AUTHENTICATOR)});1===e("input#auth-cnep-authenticator-edit-button").length&&e("input#auth-cnep-authenticator-edit-button").click(function(){a.incrementCounter(c.CLICK_EDIT_AUTHENTICATOR)})})()});"use strict";k.when("A","client-side-counters-util","mobile-auth-platform","3p-promise","ready").register("auth-cnep-webauthn-info",function(b,a,e,c){function d(b){"object"===u.type(b)?a.incrementCounter(n.IS_USER_VERIFYING_PLATFORM_AUTHENTICATOR_AVAILABLE_ERROR):
(y=b,a.incrementCounter(n.IS_USER_VERIFYING_PLATFORM_AUTHENTICATOR_AVAILABLE_SUCCESS));w=!0}function f(b){!b||b.error?a.incrementCounter(n.GET_APPINFO_ERROR):(t={appIdentifier:b.appIdentifier,platform:b.platform,mapVersion:b.mapVersion},a.incrementCounter(n.GET_APPINFO_SUCCESS));l=!0}function g(a,b,g){g=(g||"").trim();if(""!==g){var c="input[name\x3d'"+b+"']";0<a.find(c).length?a.find(c).val(g):u("\x3cinput\x3e").attr({type:"hidden",name:b,value:g}).appendTo(a)}}function m(a){a.closest("li").addClass("a-hidden aok-hidden")}
function h(){var b=new Date;return new c(function(g){var c=null;c=setInterval(function(){w&&l?(clearInterval(c),g()):500<new Date-b&&(l=w=!0,a.incrementCounter(n.MAP_CALL_TIMEOUT),clearInterval(c),g())},20)})}var u=b.$,k=Object.freeze({webAuthNCapable:"webAuthNCapable",appIdentifier:"appIdentifier",platform:"platform",mapVersion:"mapVersion"}),q=Object.freeze({major:6,minor:12,patch:9}),n=Object.freeze({WEBAUTHN_CAPABLE:"WebAuthNCapable:True",WEBAUTHN_INCAPABLE:"WebAuthNCapable:False",GET_APPINFO_SUCCESS:"GetCurrentAppInfo:Success",
GET_APPINFO_ERROR:"GetCurrentAppInfo:Error",IS_USER_VERIFYING_PLATFORM_AUTHENTICATOR_AVAILABLE_SUCCESS:"IsUserVerifyingPlatformAuthenticatorAvailable:Success",IS_USER_VERIFYING_PLATFORM_AUTHENTICATOR_AVAILABLE_ERROR:"IsUserVerifyingPlatformAuthenticatorAvailable:Error",MAP_CALL_TIMEOUT:"MAPCallTimeout"}),y=!1,t={},w=!1,l=!1;(function(){if(!(1>u("input#auth-cnep-authenticator-add-button").length)){var b=u("input#auth-cnep-authenticator-add-button").closest("form"),c=!1,r=!1,B="C";0<b.find("input[name\x3d'webAuthNEnrollExperimentWeblabTreatment']").length&&
(c=!0,B=b.find("input[name\x3d'webAuthNEnrollExperimentWeblabTreatment']").val(),b.find("input[name\x3d'webAuthNEnrollExperimentWeblabTreatment']").remove());0<b.find("input[name\x3d'shouldShowWebAuthNEnrollByEmailPattern']").length&&(r="true"===b.find("input[name\x3d'shouldShowWebAuthNEnrollByEmailPattern']").val(),b.find("input[name\x3d'shouldShowWebAuthNEnrollByEmailPattern']").remove());r||c?(e.isUserVerifyingPlatformAuthenticatorAvailable(d,500),e.getCurrentAppInfo(f,500),h().then(function(){var c;
if(c=!u.isEmptyObject(t)&&!0===y){c=t.platform;var d=t.mapVersion;if("string"!==u.type(d)||"string"!==u.type(c))c=!1;else if("Android"===c)c="20220318N"<=d;else{var f=d.split(".");c=parseInt(f[0]||"0");d=parseInt(f[1]||"0");f=parseInt(f[2]||"0");c=isNaN(c)||isNaN(d)||isNaN(f)?!1:c!==q.major?c>q.major:d!==q.minor?d>q.minor:f>=q.patch}}c?(a.incrementCounter(n.WEBAUTHN_CAPABLE),c=!0):(a.incrementCounter(n.WEBAUTHN_INCAPABLE),c=!1);c?r||"T1"===B?(g(b,k.webAuthNCapable,"true"),g(b,k.appIdentifier,t.appIdentifier),
g(b,k.platform,t.platform),g(b,k.mapVersion,t.mapVersion),b.closest("li").removeClass("a-hidden aok-hidden")):m(b):m(b)})):(l=w=!0,m(b));b.submit(function(a){if(w&&l)return!0;a.preventDefault();setTimeout(function(){b.submit()},20)})}})()});"use strict";k.when("A","client-side-counters-util","IdentityWebAuthn","3p-promise","ready").register("auth-cnep-passkey",function(b,a,e){function c(a){a.closest("li").addClass("a-hidden aok-hidden")}var d=b.$,f=Object.freeze({WEBAUTHN_SUPPORTED:"WebAuthNSupported:True",
WEBAUTHN_NOT_SUPPORTED:"WebAuthNSupported:False",WEBAUTHN_ERROR:"WebAuthNSupported:Error",CLICK_SETUP_PASSKEY:"CNEPClickAddPasskey",CLICK_EDIT_PASSKEY:"CNEPClickEditPasskey"});(function(){if(d("input#auth-cnep-passkey-setup-button").length){var b=d("input#auth-cnep-passkey-setup-button").closest("form");e.getWebAuthn().isWebAuthnSupported().then(function(g){g?(a.incrementCounter(f.WEBAUTHN_SUPPORTED),b.closest("li").removeClass("a-hidden aok-hidden")):(a.incrementCounter(f.WEBAUTHN_NOT_SUPPORTED),
c(b))}).catch(function(g){a.incrementCounter(f.WEBAUTHN_ERROR);c(b)})}})();(function(){1===d("input#auth-cnep-passkey-setup-button").length&&d("input#auth-cnep-passkey-setup-button").click(function(){a.incrementCounter(f.CLICK_SETUP_PASSKEY)});1===d("input#auth-cnep-passkey-edit-button").length&&d("input#auth-cnep-passkey-edit-button").click(function(){a.incrementCounter(f.CLICK_EDIT_PASSKEY)})})()});"use strict";k.when("auth-contact-verification-handler","ready").register("auth-contact-verification-autostart",
function(b){return b.create()});"use strict";k.when("A","auth-form-field-utils","cvf","client-side-counters-util","ready").register("auth-contact-verification-handler",function(b,a,e,c){function d(d){var h=this;d=d||{};this.postVerificationSuccessCallback=d.postVerificationSuccessCallback||g.noop;this.$verificationForm=g("form.auth-contact-verification-form");this.$contactVerificationWidgetTarget=g(".auth-contact-verification-widget-target").first();this.$claimToken=this.$verificationForm.find('input[type\x3d"hidden"].auth-contact-verification-claim-token');
this.$verifyContactButton=this.$verificationForm.find(".auth-contact-verification-button");this.contactVerificationEndpoint=this.$verificationForm.attr("action");this.postVerificationFormAction=this.$verificationForm.data("post-verification-action");this.$verificationTarget=this.$verificationForm.find(".auth-contact-verification-target");this.$spinnerTarget=this.$verificationForm.find(".auth-contact-verification-spinner");this.$successMessage=this.$verificationForm.find(".auth-contact-verification-success-message");
this.preVerify="preVerify";this.pendingVerify="pendingVerify";this.verifyState=h.preVerify;this.formSubmitEvent="submit.contactVerification";this.$reverifyOnChangeTarget=g(".auth-require-reverify-on-change, .auth-require-reverify-on-change :input");this.verificationFlowCompleteTime=this.verifyRequestCompleteTime=this.verificationFlowStartTime=0;this.disableTargetLabelCssClass="a-color-tertiary";this.errorCodes="\x26errorCodes\x3d";this.internalError="INTERNAL_ERROR";this.ajax=function(a,c){b.ajax(a,
c)};this.startContactVerification=function(){h.verificationFlowStartTime=(new Date).getTime();h.ajax(h.contactVerificationEndpoint,{method:"post",cache:!1,params:f(h.$verificationForm),error:h.startContactVerificationError,success:h.initializeComposableVerificationWidget})};this.startContactVerificationError=function(a,b,g){k.log("Error contacting contact verification endpoint: "+g+". Customers will not be able to verify their contact information.","INFO");c.incrementCounter("contactVerificationAjaxFailureContactVerificationInit");
l.location.href=l.location.href+h.errorCodes+h.internalError};this.cvfWidgetFactory=e;this.initializeComposableVerificationWidget=function(a){a=a||{};a.location?l.location.href=a.location:(a=a.requestToken||"",h.verifyRequestCompleteTime=(new Date).getTime(),a={target:h.$contactVerificationWidgetTarget,requestToken:a,onSuccess:h.completeContactVerification,onError:h.widgetInitializationError,autoStart:!1},h.$spinnerTarget&&(a.spinnerTarget=h.$spinnerTarget),h.cvfWidgetFactory.create(a).start())};
this.widgetInitializationError=function(a,b,g){k.log("Error initializing verification widget: "+g+". Customers will not be able to verify their contact information.","INFO");c.incrementCounter("contactVerificationAjaxFailureWidgetInit");l.location.href=l.location.href+h.errorCodes+h.internalError};this.setClaimToken=function(a){h.$claimToken.val(a)};this.completeContactVerification=function(b,d){h.verificationFlowCompleteTime=(new Date).getTime();d?(h.setClaimToken(b),h.setPostVerificationAction(),
h.$successMessage.show(),h.$verificationForm.unbind(h.formSubmitEvent),h.$verificationTarget.each(function(){a.enableInput(g(this));var b=g("label[for\x3d'"+g(this).attr("id")+"']");b.length&&b.removeClass(h.disableTargetLabelCssClass)}),c.insertCounter("contactVerificationCompleteVerificationFlowCompleteTime",h.verificationFlowCompleteTime-h.verificationFlowStartTime),c.insertCounter("contactVerificationVerifyRequestCompleteTime",h.verifyRequestCompleteTime-h.verificationFlowStartTime),g.isFunction(h.postVerificationSuccessCallback)&&
h.postVerificationSuccessCallback()):l.location.href=l.location.href+h.errorCodes+h.internalError};this.setPostVerificationAction=function(){h.$verificationForm.prop("action",h.postVerificationFormAction)};this.verificationRequestHandler=function(a){a.preventDefault();h.$spinnerTarget&&h.$spinnerTarget.show();h.verifyState=h.pendingVerify;h.$verifyContactButton.hide();h.startContactVerification()};this.bindVerificationFormEvent=function(){h.$verificationForm.bind(h.formSubmitEvent,h.verificationRequestHandler)};
h.bindVerificationFormEvent();this.unbindVerificationFormEvent=function(){h.$verificationForm.unbind(h.formSubmitEvent)};this.safeBind=function(){h.unbindVerificationFormEvent();h.bindVerificationFormEvent()};this.resetContactVerificationOnRequestInfoChange=function(){h.$reverifyOnChangeTarget.bind("keyup",function(a){a.preventDefault();a=13===a.keyCode;h.verifyState===h.preVerify||a||(b.trigger("cvf:claim:changed"),h.verifyState=h.preVerify,h.reVerifyEmail());h.$claimToken.val()&&h.safeBind()})};
h.resetContactVerificationOnRequestInfoChange();this.reVerifyEmail=function(){h.$contactVerificationWidgetTarget.empty();h.$verifyContactButton.show();h.$successMessage.hide();h.disableVerificationTarget();h.$verificationForm.prop("action",h.contactVerificationEndpoint)};this.disableVerificationTarget=function(){h.$verificationTarget.each(function(){a.disableInput(g(this));var b=g("label[for\x3d'"+g(this).attr("id")+"']");b.length&&b.addClass(h.disableTargetLabelCssClass)})}}function f(b){b=b.find("input.auth-contact-verification-request-info, input[type\x3dhidden]");
return a.inputsToJson(b)}var g=b.$;return{create:function(a){c.incrementCounter("contactVerificationCVFCreate");return new d(a)},ContactVerificationHandler:d}});"use strict";k.when("A").register("auth-cookie",function(b){function a(a,c,g){if(a){var d="";b.isFiniteNumber(g)&&(0>g?d="; expires\x3dThu, 01 Jan 1970 00:00:00 GMT":(d=new Date,d.setDate(d.getDate()+g),d="; expires\x3d"+d.toGMTString()));document.cookie=a+"\x3d"+l.encodeURIComponent(c)+d;return!0}return!1}function e(a){if(0<document.cookie.length&&
a){var b=document.cookie.indexOf(a+"\x3d");if(-1<b)return b=b+a.length+1,a=document.cookie.indexOf(";",b),-1===a&&(a=document.cookie.length),l.decodeURIComponent(document.cookie.substring(b,a))}return""}function c(b){a(b,"",-1)}return{setCookie:a,getCookieValue:e,deleteCookie:c,checkCookieEnabled:function(b){a("amznTest","1");var d=e("amznTest");d?c("amznTest"):b&&(b=document.getElementById(b))&&(b.style.display="block");return!!d}}});"use strict";k.when("A","phone_verification_called_within_one_minute",
"ready").register("auth-pv-resend-utility",function(b,a){return{successHandler:function(a,b){a.show();b.show()},errorHandler:function(b,c,d,f,g,m){if(403===b.http.status)l.location=c.sessionTimeoutUrl;else{b=b.http.response||"";if(0<=b.search("Throttled"))d.show();else if(0<=b.search("CalledWithinOneMinute")){if(m)return a.showErrorMessage();d.show()}else f.show();g.show()}},hideMessageBox:function(a,b,d,f,g){a.hide();b.hide();d.hide();f.hide();g.hide()}}});k.when("A","auth-pv-resend-utility","ready").register("auth-pv-resend",
function(b,a){var e=b.state("auth-pv-page-state");if(e){var c=b.$,d=c("#auth-pv-client-side-success-box"),f=c(".auth-pv-client-side-success-messages li"),g=c("#auth-pv-client-side-error-box"),m=c(".auth-pv-client-side-error-messages li"),h=c(".auth-server-side-message-box"),k=c("#auth-resend-code-succeeded"),r=c("#auth-there-was-an-error-throttled"),q=c("#auth-there-was-an-error"),n=c("#auth-resend-code-link"),y=c("#calledWithinOneMinuteReadyForResend"),t=function(){a.successHandler(k,d)},l=function(b){a.errorHandler(b,
e,r,q,g,!0)};n.click(function(c){a.hideMessageBox(d,f,g,m,h);y.hide();b.ajax(e.resendUrl,{method:"post",success:t,error:l})});return{successHandler:t,errorHandler:l}}});k.when("A").register("auto-verification-timeout",function(b){var a=b.$,e=a("#auth-auto-verification-failed");e.length&&b.delay(function(){e[0].click()},3E4)});"use strict";k.when("A","ready").register("counters-name",function(b){return{getCommonCounterNamePrefix:function(){var a="unknown",e=l.location.pathname.split("/");0<e.length&&
(a=e[e.length-1]);e="";var c=b.state("auth-csm-page-state");c&&(e=c.assocHandle);return["AuthenticationPortal",a,e].join(":")}}});"use strict";k.when("A","client-side-counters-util","mobile-auth-platform","ready").execute("retrieve-customer-information",function(b,a,e){var c=b.$;b=b.state("smartLockAttrs");console.debug("smartLockAttrs",b);if(b&&b.isSupported&&(b=b.weblab)&&"C"!==b){var d=e.CONSTANT.CustomerInformationHintType,f=0<c("#ap_email").length&&0===c("#ap_phone_number").length,g=function(){if(0===
c("select#auth-country-picker").length)return[];var a=c("select#auth-country-picker option[selected]");a={callingCode:"+"+a.data("callingCode"),countryCode:a.data("countryCode")};var b=c("select#auth-country-picker option").map(function(a,b){a=c(b);return{callingCode:"+"+a.data("callingCode"),countryCode:a.data("countryCode")}}).toArray();b.unshift(a);return b}(),m=function(a,b){a.val(b);a.data("smartlockPopulate",b)},h=function(a){a.name&&m(c("#ap_customer_name"),a.name);a.namePron&&m(c("#ap_customer_name_pronunciation"),
a.namePron);a.email&&m(c("#ap_email"),a.email);if(a.phoneNumber)if(0<c("select#auth-country-picker").length){for(var b=!1,d=0;d<g.length;d++){var e=g[d];if(a.phoneNumber.startsWith(e.callingCode)){b=a.phoneNumber.substr(e.callingCode.length);k.when("a-dropdown").execute(function(a){a.getSelect("auth-country-picker").setValue(e.countryCode)});m(c("#ap_phone_number"),b);b=!0;break}}b||m(c("#ap_phone_number"),a.phoneNumber)}else f?m(c("#ap_email"),a.phoneNumber):m(c("#ap_phone_number"),a.phoneNumber)},
u=function(a,b,g){a.bind(b,function(a){try{g.apply(this,arguments)}finally{c(this).unbind(a)}})},r=function(b){console.debug("customerInfoResult",b);b.resultType?(a.incrementCounter("GetCustomerInformationHint:RESULT:"+b.resultType),"OK"===b.resultType&&h(b.information)):a.incrementCounter("GetCustomerInformationHint:ERROR")},q=[];q=f?{T1:[d.NAME,d.EMAIL,d.PHONE],T2:[d.NAME,d.EMAIL],T3:[d.PHONE]}[b]:{T1:[d.NAME,d.EMAIL],T2:[d.NAME,d.EMAIL],T3:[d.PHONE]}[b];var n=c("#register_accordion_header");0<
n.length?"true"===n.parent().attr("aria-checked")?(a.incrementCounter("GetCustomerInformationHint:landingOnRegistration"),e.getCustomerInformationHint(q,r)):u(n,"click",function(){a.incrementCounter("GetCustomerInformationHint:switchToRegistration");e.getCustomerInformationHint(q,r)}):e.getCustomerInformationHint(q,r);f||"T1"!==b||u(c("#ap_phone_number"),"focusin",function(){a.incrementCounter("GetCustomerInformationHint:typingOnPhone");e.getCustomerInformationHint([d.PHONE],r)});c("#ap_register_form").submit(function(b){c("#ap_customer_name, #ap_customer_name_pronunciation, #ap_email, #ap_phone_number").each(function(b,
g){b=c(g);var d=b.data("smartlockPopulate");d&&d!==b.val()&&a.incrementCounter("GetCustomerInformationHint:CHANGED:"+g.id)})})}});"use strict";k.when("A","AuthToolkit","client-side-counters-util","ready").register("disable-button",function(b,a,e){var c=b.$,d=c("span.auth-disable-button-on-submit");typeof d!==x&&0<d.length&&d.closest("form").bind("submit",function(){a.disableButton(d);b.delay(function(){e.incrementCounter("NoPostbackFromSubmit");a.enableButton(d)},4E3)})});"use strict";k.when("A",
"ready").register("auth-footer-language-picker",function(b){b.on("a:dropdown:selected:languagePicker",function(a){l.location.href=a.value})});k.when("A").execute(function(b){b.declarative("other-languge-option-click","click",function(a){"input"===a.targetTag&&(l.location.href=a.$target[0].value)})});"use strict";k.when("A").register("auth-form-field-utils",function(b){function a(a){a.prop("disabled",!1);a.removeClass("a-form-disabled");a.find("input").prop("disabled",!1)}function e(a){a.removeClass("a-button-disabled");
a.find("input").prop("disabled",!1)}function c(a){a.prop("disabled",!0);a.addClass("a-form-disabled");a.find("input").prop("disabled",!0)}function d(a){a.addClass("a-button-disabled");a.find("input").prop("disabled",!0)}var f=b.$;return{enableTextInput:a,enableButton:e,enableInput:function(b){0<b.closest(".a-button").length?e(b):(b.hasClass("a-input-text")||b.hasClass("a-input-text-wrapper"))&&a(b)},disableTextInput:c,disableButton:d,disableInput:function(a){0<a.closest(".a-button").length?d(a):(a.hasClass("a-input-text")||
a.hasClass("a-input-text-wrapper"))&&c(a)},inputsToJson:function(a){return a.map(function(){var a=f(this);if(a.is("input")){var b={};b[a.attr("name")]=a.val();return b}}).toArray().reduce(function(a,b){return f.extend(a,b)})}}});"use strict";k.when("A","AmazonHelpPopup","ready").execute(function(b,a){b.$("#auth-amazon-help-link").click(function(){return a(this.href,"AmazonHelp","width\x3d700,height\x3d800,resizable\x3d1,scrollbars\x3d1,toolbar\x3d1,status\x3d1")})});k.when("A").execute(function(b){b.declarative("auth-popup",
"click",function(a){var b=a.data;a=a.$target.closest("a")[0];(b=l.open(a.href,a.target,b.windowOptions))&&b.focus()})});k.when("auth-cookie","ready").execute(function(b){b.checkCookieEnabled("auth-cookie-warning-message")});k.when("A","ready").register("AuthToolkit",function(b){function a(a){"undefined"!==typeof d(a)&&d(a).hasClass("a-button-disabled")&&(d(a).removeClass("a-button-disabled"),c(a).attr("disabled",!1))}function e(f,g){var m=c(f),h=m.data("remaining"),k=m.data("unit");0===h?(a(f),d(f).find(".a-button-text").text(g),
b.trigger("AuthToolkit.countDownEnd",f)):0<h&&(m.data("remaining",h-1),d(f).find(".a-button-text").text(k.replace(/%d/,h)),b.delay(function(){e(f,g)},1E3))}function c(a){var b=d(a).find("button");return 0<b.length?b:d(a).find("input")}var d=b.$;return{disableButton:function(a){"undefined"===typeof d(a)||d(a).hasClass("a-button-disabled")||(d(a).addClass("a-button-disabled"),c(a).attr("disabled","disabled"))},enableButton:a,countingDown:function(a){if("undefined"!==typeof d(a)){var b=d(a).find(".a-button-text").text();
0<=c(a).data("remaining")&&e(a,b)}}}});"use strict";k.when("A").register("handle-ios-redirect",function(b){document.getElementById("returnToUrl")&&0!==document.getElementById("returnToUrl").getElementsByTagName("a").length&&(l.location.href=document.getElementById("returnToUrl").getElementsByTagName("a")[0].href)});"use strict";k.when("A").register("wechat",function(b){function a(a,b){return e.ajax({url:"https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js",dataType:"script",success:a,error:b,
cache:!0})}var e=b.$,c=!1,d=null;return{WxLogin:function(b,g){g&&e.isFunction(g)||(g=function(){});c?g(new d(b)):a(function(){c=!0;d=l.WxLogin;g(new d(b));e("#identity-provider-pagelet-wechat-gray-block").fadeOut()},function(){g()})}}});k.when("A","wechat","ready").execute(function(b,a){b=b.$;b=b("#auth-identity-provider-wechat-qrcode-container");0!==b.length&&(a.WxLogin({id:"auth-identity-provider-wechat-qrcode-container",appid:b.data("appid"),scope:b.data("scope"),redirect_uri:b.data("redirect-uri"),
state:b.data("state"),style:b.data("style")}),setTimeout(function(){l.location.reload()},9E5))});"use strict";k.when("A","auth-captcha-cf").register("auth-image-captcha",function(b){function a(a){a&&a.captchaImageUrl&&d.test(a.captchaImageUrl)?(c("#auth-captcha-image").attr("src",a.captchaImageUrl),c("input[type\x3d'hidden'][name\x3d'ces']").val(a.cesString)):(k.log("Failed to load new CAPTCHA due to invalid response from server","FATAL","auth-captcha"),l.location.reload(!0))}function e(){c("#auth-captcha-refresh-link").hide();
c("#auth-captcha-noop-link").show();c("#auth-captcha-image").hide();c("#auth-captcha-image-container").addClass("a-lazy-loaded");var a=c("#auth-captcha-image").attr("data-refresh-url");a||k.log("Attempting to instantiate Captcha without a valid refresh url.","FATAL","auth-captcha");b.ajax(a,f)}var c=b.$,d=/^(http|https):\/\//,f={cache:!1,timeout:1E3,error:function(){k.log("Failed to refresh CAPTCHA due to error response from server","FATAL","auth-captcha");l.location.reload(!0)},success:a};c("#auth-captcha-image").load(function(){c("#auth-captcha-noop-link").hide();
c("#auth-captcha-refresh-link").show();c("#auth-captcha-image-container").removeClass("a-lazy-loaded");c("#auth-captcha-image").fadeIn()});c(document).delegate("#auth-captcha-refresh-link","click",function(a){a.preventDefault();e();c("#auth-captcha-guess").focus()});return{handleSuccess:a,refresh:e}});"use strict";k.when("A","ready").execute(function(b){var a=b.$("#auth-external-javascript").data("external-javascripts");a&&a.length&&b.each(a,function(a){k.load.js(a,function(a){a.target.setAttribute("crossorigin",
"anonymous")})})});"use strict";k.when("A","ready").register("auth-login-autofill",function(b){function a(a){var b=a.data("claim");a.val()!==b&&a.val(b)}function e(a,b){a=c(a);a.change(function(){b(c(this))});b(a)}var c=b.$;e("#ap-credential-autofill-hint",a);return{monitorForChanges:e,restoreClaimValue:a}});"use strict";k.when("A","auth-validate-form-common","a-form-controls-api","client-side-counters-util","page-util","ready").register("auth-moa",function(b,a,e,c,d){var f=b.$,g=f("#ap_phone_number"),
m=f("#ap_email");f("#ap_use_mobile, #ap_use_email").click(function(a){f(".ap_email_fields,.ap_mobile_number_fields").toggle();f("#auth-country-picker, #ap_email, #ap_phone_number").prop("disabled",function(a,b){return!b});f("#auth-country-picker-container").toggleClass("a-button-disabled");d.isMobile()?f("#ap_email, #ap_phone_number").parent(".a-input-text-wrapper").toggleClass("a-form-disabled"):f("#ap_email, #ap_phone_number").toggleClass("a-form-disabled");return!1});f("#ap_use_email").click(function(){a.isNonBlankField(g)&&
a.isValidEmailField(g)&&(m.val(g.val()).keyup(),c.incrementCounter("PersistEmailFromPhoneToEmail"+d.determineDeviceType()))});f("#ap_use_mobile").click(function(){a.isNonBlankField(m)&&a.isValidPhoneNumberField(m)&&(g.val(m.val()).keyup(),c.incrementCounter("PersistPhoneFromEmailToPhone"+d.determineDeviceType()))})});"use strict";k.when("A").execute(function(b){function a(a){var c=b.state("moa_registration_v2_info");c&&c.enabled&&b.get("/ap/nocontent/ref\x3d"+a+"_"+c.device,{})}var e=b.$;e("#ap_use_email").click(function(){a("ap_mmoar_usee")});
e("#ap_use_mobile").click(function(){a("ap_mmoar_usem")});e("#auth-country-picker-container").click(function(){a("ap_mmoar_ccp")});e("#continue").click(function(){a("ap_mmoar_cont")});b.on("a:popover:show:verifyContinueModal",function(){a("ap_mmoar_vm_o")});b.on("a:popover:hide:verifyContinueModal",function(){a("ap_mmoar_vm_c")});e("#auth-verification-ok-announce").click(function(){a("ap_mmoar_vm_ok")});e("#auth-already-have-account").click(function(){a("ap_mmoar_signin")});e("#auth-verify-button").click(function(){a("ap_mmoar_pv_verify")});
e("#auth-resend-code-link").click(function(){a("ap_mmoar_pv_resend")})});"use strict";k.when("A","moa-single-claim-input-field_handler","ready").register("moa-single-claim-input-field",function(b,a){var e=b.$;e("#ap_email");b.declarative("single_claim_handler","focusout keyup",a.inputHandler);b.declarative("show-countries","click",a.showCountries);b.on("a:dropdown:auth-country-picker:select",a.updateCountryDisplayText)});"use strict";k.when("A","auth-validate-form-common","client-side-counters-util",
"mobile-claim-disclosure-util").register("moa-single-claim-input-common",function(b,a,e,c){function d(b){return a.isNonBlankField(b)?a.isValidPhoneNumberField(b)?g.PHONE:g.EMAIL:g.UNKNOWN}var f=b.$,g={PHONE:"PHONE",EMAIL:"EMAIL",UNKNOWN:"UNKNOWN"};Object.freeze(g);var m={};m[g.PHONE]="phone-text";m[g.EMAIL]="email-text";m[g.UNKNOWN]="default-text";Object.freeze(m);var h={};h[g.PHONE]="SingleClaimFieldPhone";h[g.EMAIL]="SingleClaimFieldEmail";Object.freeze(h);var k={REGISTER:"registerPage",SIGNIN:"signInPage"};
Object.freeze(k);var r=c.DisclosureType;f.fn.auiShow=function(){f(this).removeClass("a-hidden aok-hidden").show();return this};f.fn.auiHide=function(){f(this).addClass("aok-hidden").hide();return this};return{showPasswordInformationMessage:function(a){a=a&&a.$currentTarget||f(a.target);a.closest(".a-row").parent().find(".auth-inlined-error-message").is(":visible")||a.closest(".a-row").parent().find("#passwordInformationMessage").auiShow()},hidePasswordInformationMessage:function(a){var c=a&&a.$currentTarget||
f(a.target);c.closest(".a-row").parent().find("#passwordInformationMessage").auiHide();a.$event&&a.$event.relatedTarget&&"submit"===a.$event.relatedTarget.type&&b.delay(function(){c.closest("form").submit()})},incrementCounterForSelectedClaim:function(a){a=d(a);e.incrementCounter(e.getCounterNameWithDeviceAndPageType(h[a]))},incrementCounterForPlusSymbolAtStartOfClaim:function(){e.incrementCounter(e.getCounterNameWithDeviceAndPageType("PlusSymbolAtStartOfClaim"))},incrementCounterForToggleCountryPicker:function(a){e.incrementCounter(e.getCounterNameWithDeviceAndPageType(a?
"CountryPickerEnabled":"CountryPickerDisabled"))},getClaimType:d,getDisclosureType:function(a,b){a=a.val()&&a.val().trim()||"";if(a.startsWith("+"))return c.getDisclosureTypeByPhoneNumber(a);b=(b()||"").trim();return c.getDisclosureTypeByCountryCode(b)},ClaimType:g,PageType:k,DisclosureType:r,ButtonTextToClass:m,isValidEmail:/^([a-zA-Z0-9_\.\-\+])+@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,invalidPhoneRegex:/^ *\+|[a-zA-Z]|@/}});"use strict";k.when("A","auth-validate-form-common","client-side-counters-util",
"moa-single-claim-input-common","a-dropdown").register("moa-single-claim-input-field_handler",function(b,a,e,c,d){function f(a){n("#auth-continue .a-button-text span").auiHide();n("#auth-continue ."+a).auiShow()}function g(a){var b=a.closest(".a-section").find(".country-picker");if(b&&k(a)){var c=b.outerWidth();n.withoutRtl(function(){a.css({"padding-left":c+"px"})})}else n.withoutRtl(function(){a.css({"padding-left":""})})}function m(a,b){a=a.closest(".moa-single-claim-container").find("select").attr("id");
d.getSelect(a).update({status:b})}function h(a){k(a)&&(m(a,"disabled"),a.closest(".a-section").find(".country-picker").auiHide(),g(a),c.incrementCounterForToggleCountryPicker(!1))}function k(a){return a.closest(".a-section").find(".country-picker").is(":visible")}function r(a){c.getDisclosureType(a,function(){return n("select#auth-country-picker").val()})===c.DisclosureType.RIGID?(a.closest(".a-box").find("#mobileClaimDisclosureMessage").auiShow(),a.closest(".a-box").find("#mobileClaimDisclosureMessageRelaxed").auiHide()):
(a.closest(".a-box").find("#mobileClaimDisclosureMessageRelaxed").auiShow(),a.closest(".a-box").find("#mobileClaimDisclosureMessage").auiHide());a=n("input[name\x3d'addMobilePhoneLegalMessageExperimentTreatment']");0<a.length&&("T1"!==a.val()&&"C"!==a||e.triggerWeblab("CJ_AUTHX_597245",a.val()),a.remove())}function l(a){0>=a.size()||(c.getClaimType(a)===c.ClaimType.PHONE?r(a):(a.closest(".a-box").find("#mobileClaimDisclosureMessage").auiHide(),a.closest(".a-box").find("#mobileClaimDisclosureMessageRelaxed").auiHide()))}
var n=b.$;return{inputHandler:function(a){var b=a.$currentTarget.find("input");if("focusout"===a.type){var d=a.$currentTarget.find("input");if(!(0>=d.size()))switch(c.getClaimType(d)){case c.ClaimType.PHONE:f(c.ButtonTextToClass.PHONE);break;case c.ClaimType.EMAIL:f(c.ButtonTextToClass.EMAIL);break;default:f(c.ButtonTextToClass.UNKNOWN)}l(b)}if("focusout"===a.type||"keyup"===a.type)b=a.$target,d=b.val()&&b.val().trim()||"",a=a.$event.which,16<=a&&46>a||(c.getClaimType(b)!==c.ClaimType.PHONE||d.startsWith("+")?
d.startsWith("+")?(h(b),c.incrementCounterForPlusSymbolAtStartOfClaim()):h(b):k(b)||(m(b,"enabled"),b.closest(".a-section").find(".country-picker").auiShow(),g(b),c.incrementCounterForToggleCountryPicker(!0)))},showCountries:function(a){a.$currentTarget.closest(".moa-single-claim-container").find(".moa-country-picker-select-container .a-declarative").click()},updateCountryDisplayText:function(a){var b=n(a.selectNode),c=b.closest(".moa-single-claim-container").find(".country-picker");b=b.closest(".moa-single-claim-container").find("input[name\x3demail]");
a=a.nativeItemNode.text;c.find(".a-declarative").text(a);g(b);l(b)}}});"use strict";k.when("A").register("mobile-claim-disclosure-util",function(b){var a=b.$,e={RIGID:"RIGID",RELAXED:"RELAXED"};Object.freeze(e);var c=["+1","+33"],d=["US","CA","FR"];Object.freeze(c);Object.freeze(d);return{DisclosureType:e,getDisclosureTypeByCountryCode:function(a){for(var b=0;b<d.length;b++)if(d[b]===a.toUpperCase())return e.RIGID;return e.RELAXED},getDisclosureTypeByPhoneNumber:function(a){for(var b=0;b<c.length;b++)if(a.startsWith(c[b]))return e.RIGID;
return e.RELAXED},showMobileClaimDisclosureMessage:function(b){a(b).removeClass("a-hidden aok-hidden").show();return this},hideMobileClaimDisclosureMessage:function(b){a(b).addClass("aok-hidden").hide();return this}}});"use strict";k.when("A").register("page-util",function(b){function a(a){return d(a).is(":visible")?e(d(a).attr("name")):null}function e(a){if(a)return a.replace(/(?:-| |\b)(\w)/g,function(a,b){return b.toUpperCase()})}function c(){return b.capabilities.mobile}var d=b.$;return{getFormName:a,
toCamelCase:e,determinePageType:function(){for(var b={SignIn:"SignInPage",Register:"RegistrationPage",ForgotPassword:"Fpp"},c=document.getElementsByTagName("form"),d=0;d<c.length;d++){var e=a(c[d]);if(e in b)return b[e]}},determineDeviceType:function(){return c()?"OnMobile":"OnDesktop"},isMobile:c}});"use strict";k.when("A","ready").execute("password-encryption-setup",function(b){var a=b.state("sif-encryption-profile");a&&k.when("auth-validate-form-handler","siege-cse:profile:"+a.sifProfile).execute("password-encryption",
function(e,c){function d(d){function g(a){b.$(d).unbind(".encryption").submit()}try{var e=c.createFormHandler(d);e.configure({formProfile:a.sifProfile,encryptionContext:{}});var h=b.$(d).find("input[name\x3d'password']").val().length;e.generateProcessedForm({}).then(function(a){var c=b.$(a).find("input[name\x3d'password']").val().length;h===c&&(c=document.createElement("INPUT"),c.setAttribute("type","hidden"),c.setAttribute("name","passwordNotEncrypted"),a.appendChild(c));b.$(a).find("input[name\x3d'password']").get(0).name=
"encryptedPwd";a.submit()}).catch(g)}catch(u){g(u)}}b.$("input[name\x3d'password']").closest("form").not("#ap_register_form").bind("submit.encryption",function(a){a.preventDefault();e.validate(this)&&d(this)})})});"use strict";k.when("A","client-side-counters-util","page-util").register("passwordless-auth",function(b,a,e){var c=b.$,d=b.state("login-with-otp-state"),f=c("#ap_login_form #continue");l.loginWithOTPState=d!==x?d.isLoginWithOTPEnabled:!1;c("#auth-skip-reset-password-link").click(function(){b.get("/ap/nocontent/ref\x3dap_fpp_skip_on_reset_pwd",
{});a.incrementCounter("SkipResetPasswordOnResetPage"+e.determineDeviceType())});b.on("credentialsEntered",function(){!0===l.loginWithOTPState&&(a.incrementCounter("SharedWebCredentialsSubmitted"),f.click())})});"use strict";k.when("A","mobile-claim-disclosure-util","client-side-counters-util","ready").register("phone-number-field",function(b,a,e){function c(b){a.getDisclosureTypeByCountryCode(b)===a.DisclosureType.RELAXED?(a.hideMobileClaimDisclosureMessage("#mobileClaimDisclosureMessage"),a.showMobileClaimDisclosureMessage("#mobileClaimDisclosureMessageRelaxed")):
(a.showMobileClaimDisclosureMessage("#mobileClaimDisclosureMessage"),a.hideMobileClaimDisclosureMessage("#mobileClaimDisclosureMessageRelaxed"))}function d(a){a=f("select#auth-country-picker").val()||"";c(a)}var f=b.$;(function(){if(0<f("#ap-account-fixup-phone-non-editable-text").length&&0<f("#mobileClaimDisclosureMessage").length&&0<f("#mobileClaimDisclosureMessageRelaxed").length){var g=f("#ap-account-fixup-phone-non-editable-text").val();a.getDisclosureTypeByPhoneNumber(g)===a.DisclosureType.RELAXED?
(a.hideMobileClaimDisclosureMessage("#mobileClaimDisclosureMessage"),a.showMobileClaimDisclosureMessage("#mobileClaimDisclosureMessageRelaxed")):(a.showMobileClaimDisclosureMessage("#mobileClaimDisclosureMessage"),a.hideMobileClaimDisclosureMessage("#mobileClaimDisclosureMessageRelaxed"))}(0<f("#ap_phone_number").length||0<f("#account-fixup-phone-number").length)&&0<f("select#auth-country-picker").length&&0<f("#mobileClaimDisclosureMessage").length&&0<f("#mobileClaimDisclosureMessageRelaxed").length&&
(g=f("select#auth-country-picker").val(),c(g),g=f("input[name\x3d'addMobilePhoneLegalMessageExperimentTreatment']"),0<g.length&&("T1"!==g.val()&&"C"!==g||e.triggerWeblab("CJ_AUTHX_597245",g.val()),g.remove()),b.on("a:dropdown:auth-country-picker:select",d))})()});"use strict";k.when("A","a-modal","auth-validate-form-handler","ready").register("auth-phone-verification-modal",function(b,a,e){function c(){var a=m.val();q.text(a);var b=g.find("option:selected");a=b.data("calling-code");b=b.data("country-code");
k.text(a);l.text(b)}var d=b.$,f=b.state("auth-phone-verification-modal");if(f){var g=d("#auth-country-picker"),m=d("#ap_phone_number"),h=d("#"+f.formIdToBindTo),k=d("#auth-verify-mobile-calling-code"),l=d("#auth-verify-mobile-country-code"),q=d("#auth-verify-mobile-national-number");b.on("a:popover:beforeShow:verifyContinueModal",c);d(".auth-requires-verify-modal").click(function(b){b.preventDefault();e.validate(h)&&(b=d("#auth-verify-modal-action"),(b=a.get(b))&&m.is(":enabled")?b.show():h.submit())});
b.declarative("auth-verify-modal-complete","click",function(){h.submit()});return{updateVerificationModalContents:c}}});"use strict";k.when("A").register("auth-phone-verification-spinner",function(b){b=b.$;var a=b("#auth-contact-verification-spinner-hidden-code-form-wrapper #auth-pv-form");0<a.length&&(l.submitVerificationCode=function(b){a.find("#auth-pv-enter-code").val(b);a.find("#auth-verify-button").click()})});"use strict";k.when("A","ready").register("phone_verification_called_within_one_minute",
function(b){function a(){e.removeClass("resend-link-disabled");c.hide();f.show();g.html(g.text().replaceAll('"',""))}b=b.$;var e=b("#auth-resend-code-link"),c=b("#calledWithinOneMinuteAlert"),d=b("#calledWithinOneMinuteText"),f=b("#calledWithinOneMinuteReadyForResend"),g=b("#calledWithinOneMinuteReadyForResendText"),m="";return{showErrorMessage:function(){f.hide();if(""===m){var b=d.text().split(" +timeleft+ ");m=b[0].split('"').join("")+"60"+b[1].split('"').join("")}c.show();d.html(m);e.addClass("resend-link-disabled");
setTimeout(a,6E4)}}});"use strict";k.when("A","client-side-counters-util","a-checkbox","ready").register("auth-remember-me",function(b,a,e){function c(b){b.val()!==g?(e(m).isChecked()&&a.incrementCounter(a.getCounterNameWithDeviceAndPageType("UncheckRMCheckboxForUnrecognizedEmail")),e(m).uncheck()):""!==b.val()&&(e(m).check(),a.incrementCounter(a.getCounterNameWithDeviceAndPageType("BackToCheckedRMCheckboxForRecognizedEmail")))}b=b.$;var d=b("#ap_email, #ap-credential-autofill-hint"),f=b("#ap_email_icon"),
g=d.val(),m=b("input[name\x3drememberMe]");d.bind("keyup.uncheckRememberMe",function(){""!==g&&c(d)});f.click(function(){c(d)})});"use strict";k.when("A","client-side-counters-util","page-util","ready").register("auth-remove-mobile-claim",function(b,a,e){b=b.$;var c=b("#auth-remove-phone-claim");b("#ap-remove-mobile-claim-submit-button").click(function(){c.submit();a.incrementCounter("RemoveMobileClaimSubmitAttempt"+e.determineDeviceType())})});"use strict";k.when("A","IdentityWebAuthn").register("SignInWithPasskeyUtilities",
function(b){function a(a){var b={};f("form[name\x3d"+a+"] \x3e input[type\x3dhidden]").each(function(){b[this.name]=this.value});return b}function e(){d(g.clientErrorMessage());d(g.serverErrorMessage());c(g.genericServerErrorMessage());c(g.passkeyAlert())}function c(a){a.removeClass("aok-hidden")}function d(a){a.addClass("aok-hidden")}var f=b.$,g={passkeyAlert:function(){return f("#passkey-error-alert")},clientErrorMessage:function(){return f("#passkey-client-error-message")},genericServerErrorMessage:function(){return f("#passkey-generic-server-error-message")},
serverErrorMessage:function(){return f("#passkey-server-error-message")}};return{handleFetchPasskeySignInAssertionResponse:function(f,h,k){f.isSuccess?(h=a(h),h.completePasskeyChallengeAssertion=f.assertion,h.assertionAssociatedChallengeId=k,b.post("/ap/signin/start",{params:h,success:function(a){var b="object"===typeof a;b&&"redirect"in a?l.location.href=a.redirect:b&&"error"in a?(a=a.error,b=g.serverErrorMessage(),d(g.clientErrorMessage()),d(g.genericServerErrorMessage()),b.text(a),c(b),c(g.passkeyAlert())):
(e(),console.warn("Unexpected response from /ap/signin/start!"))},timeout:5E3,error:function(a,b,c){e();console.warn("Error communicating with /ap/signin/start: "+c)}})):(0===f.errorCodes[0].indexOf("ServerError_")?e():(d(g.genericServerErrorMessage()),d(g.serverErrorMessage()),c(g.clientErrorMessage()),c(g.passkeyAlert())),console.debug("Sign-in with passkey failed: "+f.errorCodes))}}});"use strict";k.when("jQuery","IdentityWebAuthn","SignInWithPasskeyUtilities","ready").register("auth-signin-passkey-autofill",
function(b,a,e){function c(){a.getWebAuthn().fetchPasskeySignInAssertion(g).then(function(a){e.handleFetchPasskeySignInAssertionResponse(a,"signIn",g.challengeId)}).catch(function(a){console.error(a)})}var d=b("#ap_email[autocomplete\x3dwebauthn]"),f=b("#ap_email_login[autocomplete\x3dwebauthn]");if(d.length||f.length)if(d=b("input[type\x3dhidden][name\x3dwebAuthnGetParametersForAutofill]"),b=b("input[type\x3dhidden][name\x3dwebAuthnChallengeIdForAutofill]"),d.length&&b.length){var g={serializedCredentialParameters:d.val(),
challengeId:b.val()};a.getWebAuthn().isWebAuthnSupported().then(function(a){a&&c()}).catch(function(a){console.error(a)})}});"use strict";k.when("A","IdentityWebAuthn","a-button","SignInWithPasskeyUtilities","3p-promise","ready").register("auth-signin-passkey-button",function(b,a,e,c){function d(){k("#auth-signin-via-passkey-section").addClass("a-hidden aok-hidden")}function f(){if(e("#auth-signin-via-passkey-btn").isEnabled()){e("#auth-signin-via-passkey-btn").disable();var b=g(),d={serializedCredentialParameters:b.getCredentialParametersField.val(),
challengeId:b.challengeIdField.val()};a.getWebAuthn().fetchPasskeySignInAssertion(d).then(function(a){c.handleFetchPasskeySignInAssertionResponse(a,"signInWithPasskeyButton",d.challengeId);e("#auth-signin-via-passkey-btn").enable()}).catch(function(a){e("#auth-signin-via-passkey-btn").disable();console.error(a)})}}function g(){return{getCredentialParametersField:k("input[type\x3dhidden][name\x3dwebAuthnGetParametersForButton]"),challengeIdField:k("input[type\x3dhidden][name\x3dwebAuthnChallengeIdForButton]")}}
var k=b.$;b.declarative("SIGNIN_PASSKEY_COLLECT","click",function(a){f()});k("#auth-signin-via-passkey-section").length&&a.getWebAuthn().isWebAuthnSupported().then(function(a){a?(a=g(),a.getCredentialParametersField.length&&a.challengeIdField.length?k("#auth-signin-via-passkey-section").removeClass("a-hidden aok-hidden"):d()):d()}).catch(function(a){d()})});"use strict";k.when("A","ready").register("auth-text-captcha",function(b){b=b.$;b("#auth-captcha-guess").attr("autocapitalize","off");b("#auth-captcha-guess").attr("autocorrect",
"off")});"use strict";k.when("A","auth-validate-form-handler","ready").register("auth-validate-form-moa",function(b,a){b=b.$;b(document.body).delegate(".auth-validate-form-moa","submit",function(b){a.validate(this)||b.preventDefault()})});k.when("A","auth-validate-form-handler","auth-validate-form-common","client-side-counters-util","page-util","AuthToolkit","ready").register("auth-validate-form",function(b,a,e,c,d,f){var g=b.$;g(document.body).delegate(".auth-validate-form","submit",function(b){c.incrementCounter(d.getFormName(this)+
"Submit"+e.determineDeviceType());if(!a.validate(this)){var h=g(this).find("span.auth-disable-button-on-submit.a-button-disabled");typeof h!==x&&0<h.length&&f.enableButton(h);b.preventDefault()}})});"use strict";k.when("A","page-util","a-text-input","ready").register("auth-validate-form-common",function(b,a,e){function c(a){return x.test(a.trim())}function d(a){return z.test(a.trim())}function f(a){a=a.val();return c(a)}function g(a){a=a.val();return d(a)}function k(a){a=a.val();return c(a)||d(a)}
function h(a){return 6<=a.val().length}function l(a){return"password"===a.attr("type")?r(a):q(a)}function r(a){return!!a.val()}function q(a){return!!a.val().trim()}function n(a){return a.data("validation-id")||a.parent().data("validation-id")||a[0].name}function y(a){(new e(a)).setState("error")}function t(a){(new e(a)).setState("normal")}var w=b.$,x=/^([a-zA-Z0-9_\.\-\+])+@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,z=/^\+?[()\s.0-9-]*\d[()\s.0-9-]*$/,A={"auth-required-field":"-missing-alert","auth-require-email-validaton":"-invalid-email-alert",
"auth-require-phone-validation":"-invalid-phone-alert","auth-require-claim-validation":"-invalid-claim-alert","auth-require-password-validation":"-invalid-password-alert","auth-require-fields-match":"-mismatch-alert"},p={"auth-required-field":l,"auth-require-email-validaton":f,"auth-require-phone-validation":g,"auth-require-claim-validation":k,"auth-require-password-validation":h};return{isMatchingFields:function(a){var b=a.eq(0);a=a.eq(1);b=b.val().trim();a=a.val().trim();return b===a},isValidEmailField:f,
isValidPhoneNumberField:g,isValidClaimField:k,isValidEmail:c,isValidPhoneNumber:d,isValidPasswordField:h,isValidRequiredField:l,isNonEmptyField:r,isNonBlankField:q,isCheckedField:function(a){return a.is(":checked")},displayErrorMessage:function(a,b){var c=n(a);b=w("#auth-"+c+b);y(a);b.show()},hideErrorMessage:function(a,b){var c=n(a);b=w("#auth-"+c+b);t(a);b.hide()},isErrorVisible:function(a,b){a=n(a);return w("#auth-"+a+b).is(":visible")},getValidationId:n,setTextInputStateError:y,setTextInputStateNormal:t,
determineDeviceType:function(){return a.isMobile()?"OnMobile":"OnDesktop"},getErrorAlertExtension:function(a){return A[a]},getValidateCallback:function(a){return p[a]},getErrorTypeClasses:function(){return Object.keys(p)},getVisibleInputsSelector:function(){return"input[type!\x3dhidden]:enabled"},getSelectorForInputsOfErrorTypeClass:function(a){if(a)return a+=":visible","input:enabled."+a+", ."+a+" input:enabled"}}});"use strict";k.when("A","auth-validate-form-common","client-side-counters-util",
"page-util","a-text-input","ready").register("auth-validate-form-handler",function(b,a,e,c,d){function f(b,d,g,f){var h=a.getValidationId(d);h&&(v||(v={}),v[h]||(v[h]=[]),v[h].push({$field:d,type:g,extension:f}),f&&e.incrementCounter(c.getFormName(b)+c.toCamelCase(h+f)+a.determineDeviceType()))}function g(b){b.find(".auth-require-fields-match-group").each(function(){var c=p(this).find(a.getSelectorForInputsOfErrorTypeClass("auth-require-fields-match"));1<c.length&&a.isValidRequiredField(c.eq(0))&&
a.isValidRequiredField(c.eq(1))&&!a.isMatchingFields(c)&&(f(b,c.eq(0),"Check Mismatch","-mismatch-alert"),f(b,c.eq(1),"Check Mismatch"))})}function k(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-email-validaton")).each(function(){var c=p(this);a.isNonBlankField(c)&&!a.isValidEmailField(c)&&f(b,c,"Invalid Email","-invalid-email-alert")})}function h(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-claim-validation")).each(function(){var c=p(this);a.isNonBlankField(c)&&
!a.isValidClaimField(c)&&f(b,c,"Invalid Claim","-invalid-claim-alert")})}function l(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-phone-validation")).each(function(){var c=p(this);a.isNonBlankField(c)&&!a.isValidPhoneNumberField(c)&&f(b,c,"Invalid Phone","-invalid-phone-alert")})}function r(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-password-validation")).each(function(){var c=p(this);a.isNonEmptyField(c)&&!a.isValidPasswordField(c)&&f(b,c,"Invalid Password","-invalid-password-alert")})}
function q(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-required-field")).each(function(){var c=p(this),d=this.name;a.isValidRequiredField(c)||B.test(d)&&v&&v[d.split("Check")[0]]||f(b,c,"Missing Required","-missing-alert")})}function n(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-required-checked-field")).each(function(){var c=p(this);a.isCheckedField(c)||f(b,c,"Legal Agreement Unchecked","-unchecked-alert")})}function y(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-required-field")).each(function(){var c=
p(this);"cbdtAgreementCheckBox"!==this.name||a.isCheckedField(c)||f(b,c,"Registration Legal Agreement Unchecked","-unchecked-alert")})}function t(b){c.isMobile()||b.find(a.getSelectorForInputsOfErrorTypeClass("auth-required-field")).each(function(){var c=p(this);"legalAgreementCheckBox"!==this.name||a.isCheckedField(c)?"cbdtAgreementCheckBox"!==this.name||a.isCheckedField(c)||f(b,c,"Registration Legal Agreement Unchecked","-unchecked-alert"):f(b,c,"Registration Legal Agreement Unchecked","-unchecked-alert")});
if(c.isMobile()){var d=[];b.find(a.getSelectorForInputsOfErrorTypeClass("auth-required-field")).each(function(){var b=p(this);"cbdtAgreementCheckBox"!==this.name||a.isCheckedField(b)?"legalAgreementCheckBox"!==this.name||a.isCheckedField(b)||d.push(b):d.push(b)});0<d.length&&f(b,d[0],"Legal Agreement Unchecked","-unchecked-alert")}}function w(d){var e=p("#auth-alert-window");x(p("form")).each(function(){a.setTextInputStateNormal(p(this))});p(".auth-error-messages li, .auth-inlined-error-message, .auth-inlined-information-message, .auth-server-side-message-box").hide();
v?(b.each(v,function(c,d){b.each(c,function(b){var c=b.extension;a.setTextInputStateError(b.$field);c&&(b="#auth-"+d+c,c=p(b+C),c.length?c.show():p(b).show())})}),p("#message-box-slot").hide(),e.show(),c.isMobile()?(e=d.find("input[name\x3dgiveFocusOnMobileToFirstControlFailingValidation]"),0<e.length&&"true"===e.val()&&x(d).first().focus()):x(d).first().focus()):e.hide()}function x(b){return b.find(a.getVisibleInputsSelector()).filter(function(){return(new d(p(this))).isError()})}function z(a){return"string"!==
typeof a||0===a.length?"":Array.prototype.map.call(a,function(a){var b=a.charCodeAt(0);return 65280<=b&&65519>=b?String.fromCharCode(b-65248):12288===b?String.fromCharCode(32):a}).join("")}function A(a){a.find("input[name\x3demail], input[name\x3dcustomerName], input[name\x3dcustomerNamePronunciation], input[name\x3demailLogin], input[name\x3dguess]").each(function(){if(""!==p(this).val()){var a=z(p(this).val());p(this).val()!==a&&(p(this).val(a),e.incrementCounter(e.getCounterNameWithDeviceAndPageType("SingleClaimFieldFullWidthRemoval")))}})}
var p=b.$,B=/Check$/g,C="",v;return{validate:function(b){b=b&&b.jquery?b:p(b);if(b.length&&b.is("form")){C=b.hasClass("ap_ango_phone")?"-ango-phone":b.hasClass("ap_ango_email")?"-ango-email":"";A(b);q(b);h(b);k(b);l(b);r(b);g(b);n(b);y(b);v&&e.incrementCounter(c.getFormName(b)+"PreventedServerRoundTrips"+a.determineDeviceType());w(b);var d=!v;b.data("auth-validation-errors",v);v=void 0;return d}},validateLegalCheckedForThirdParty:function(a){a=a&&a.jquery?a:p(a);if(a.length&&a.is("form")){0<document.getElementsByName("signin-legal-agreement-checkbox").length&&
n(a);0<document.getElementsByName("legalAgreementCheckBox").length&&t(a);w(a);var b=!v;a.data("auth-validation-errors",v);v=void 0;return b}},getErrors:function(a){return(a.jquery?a:p(a)).data("auth-validation-errors")},toHalfWidth:z}});"use strict";k.when("A","auth-validate-form-common","ready").register("auth-validate-form-real-time",function(b,a){function e(b,c,d){a.isErrorVisible(b,a.getErrorAlertExtension(c))&&d(b)&&a.hideErrorMessage(b,a.getErrorAlertExtension(c))}function c(b,c){if(b.hasClass("auth-require-fields-match")&&
(b=b.closest(".auth-require-fields-match-group"),b!==f&&(b=b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-fields-match")),2===b.length))){var d=b.eq(0),e=b.eq(1);a.isErrorVisible(d,a.getErrorAlertExtension("auth-require-fields-match"))&&c(b)&&(a.hideErrorMessage(d,a.getErrorAlertExtension("auth-require-fields-match")),a.setTextInputStateNormal(e))}}var d=b.$,f;d(".auth-real-time-validation input").bind("keyup.clearValidationErrors",function(){var b=d(this);e(b,"auth-required-field",a.isNonEmptyField);
e(b,"auth-require-email-validaton",a.isValidEmailField);e(b,"auth-require-phone-validation",a.isValidPhoneNumberField);e(b,"auth-require-claim-validation",a.isValidClaimField);e(b,"auth-require-password-validation",a.isValidPasswordField);c(b,a.isMatchingFields)});return{clearErrorMessageOnMatchingInputs:c}});k.when("A","auth-validate-form-common","auth-validate-form-handler","a-text-input","client-side-counters-util","ready").register("auth-validate-form-real-time-common",function(b,a,e,c,d){var f=
b.$;return{convertFullwidthToHalfWidth:function(b){if(""!==b.val()){var c=e.toHalfWidth(b.val());b.val()!==c&&(b.val(c),d.incrementCounter("FullWidthRemoval"+a.determineDeviceType()))}},recordValidations:function(b,d){var e=new c(d),g=a.getValidationId(d);f.each(a.getErrorTypeClasses(),function(c,d){b[g]||(b[g]=[]);e.hasClass(d)&&b[g].push({errorAlertExtension:a.getErrorAlertExtension(d),validate:a.getValidateCallback(d)})})},findInlineErrors:function(b,c,d){var e=[];f.each(b[d],function(b,d){if(d.validate===
a.isValidRequiredField&&!a.isValidRequiredField(c))return e.splice(0),e.push(d.errorAlertExtension),!1;a.isValidRequiredField(c)&&!d.validate(c)&&e.push(d.errorAlertExtension)});return e},displayErrors:function(b,c,e){f.each(e,function(e,f){a.isErrorVisible(b,f)||(d.incrementCounter("RealtimeValidateDisplayError"+a.determineDeviceType()+":"+c+f),a.displayErrorMessage(b,f))})},hideCorrectedErrors:function(c,e,h,k,l,q){c=c[h].map(function(a){return a.errorAlertExtension});f.each(c,function(b,c){a.isErrorVisible(e,
c)&&0>k.indexOf(c)&&(d.incrementCounter("RealtimeValidateHideCorrectedError"+a.determineDeviceType()+":"+h+c),a.hideErrorMessage(e,c))});l&&l.relatedTarget&&"submit"===l.relatedTarget.type&&9!==q&&b.delay(function(){e.closest("form").submit()})}}});"use strict";k.when("A","jQuery","ready").register("wechat-wxlogin-js",function(b,a){0<a("#auth-wechat-login-container").length&&(b=a("#auth-wechat-login-container").data("wechatUrl"),k.load.js(b))});k.when("A","jQuery","client-side-counters-util","wechat-login-button-counter",
"wechat-wxlogin-js","ready").register("wechat-qrcode-module",function(b,a,e,c){if(0<a("#auth-wechat-login-container").length){var d=function(){var b=a("div#auth-interactive-dialog-content"),c=a("div#auth-wechat-qrcode-loading-container").clone();c.removeClass("hidden");c.appendTo(b);a("div#auth-interactive-dialog").css("display","table");var d=a("#auth-wechat-login-container");b=d.data("appid");c=d.data("scope");var e=d.data("redirectUrl"),f=d.data("state");d=d.data("style");new l.WxLogin({id:"auth-wechat-qrcode-container",
appid:b,scope:c,redirect_uri:e,state:f,style:d})},f=function(){var b=a("div#auth-interactive-dialog-content");a("div#auth-interactive-dialog").css("display","none");b.empty()};a("div#auth-interactive-dialog-content").click(function(a){a.stopImmediatePropagation()});a("#auth-wechat-login-container").click(function(){e.incrementCounter(c.weChatButtonClickEventCounterName);d()});a("div#auth-interactive-dialog-container").click(function(){f()});return{showWeChatQRCode:d,hideWeChatQRCode:f}}});k.when("A",
"client-side-counters-util","counters-name","ready").register("wechat-login-button-counter",function(b,a,e){var c=e.getCommonCounterNamePrefix()+":WeChat";e=b.$("#auth-wechat-login-container-noninteractive");0<e.length&&e.click(function(){a.incrementCounter(c)});b=b.$("#signInSubmit.wechat_button");0<b.length&&b.click(function(){a.incrementCounter(c)});return{weChatButtonClickEventCounterName:c}});k.when("A","auth-validate-form-handler","ready").register("wechat-legal-checkbox-validation",function(b,
a){function e(b){b=document.getElementsByClassName(b);document.getElementById("weChatAuthenticationUri")&&a.validateLegalCheckedForThirdParty(b)&&(l.location.href=document.getElementById("weChatAuthenticationUri").value)}var c=b.$("#signInSubmit.wechat_button");0<c.length?c.click(function(){e("auth-validate-form")}):(b=b.$("#auth-wechat-login-container-noninteractive.wechat_button"),0<b.length&&b.click(function(){0<document.getElementsByClassName("auth-validate-form").length?e("auth-validate-form"):
0<document.getElementsByClassName("auth-validate-form-moa").length&&e("auth-validate-form-moa")}))})});
/* ******** */
