P.register("cvfVersion",function(){return{version:"0.1.0.0-2023-06-28"}});"use strict";
P.when("A","cvfFormDataGenerator","cvf-client-side-counters-util","ready").register("cvf-account-switcher",function(a,l,b){function m(b,c){b.preventDefault();var h=l.retrieveFormData(b.target),d=h.inputData.serializeArray();d.push(g(b.target));a.ajax(window.location.protocol+"//"+window.location.host+h.requestPath,{method:"POST",params:d,success:c,error:e})}function g(a){a=h(a);var b=a.attr("name");b||(b=a.closest(".cvf-account-switcher-sign-out-link").attr("data-name"));var c=a.attr("value");c||
(c=a.closest(".cvf-account-switcher-sign-out-link").attr("data-value"));return{name:b,value:c}}function e(b,c,h){a.trigger(r.error,h)}function d(a){var b=/([^@\s]+)@([a-zA-Z0-9_-]+)(\.[a-zA-Z0-9._-]+)/ig.exec(a);if(null!==b){a=b[1];a=h.trim(a);var c=a.length;if(1!==c){for(var d=a.charAt(0),f=0;f<c-2;f++)d+="*";a=d+=a.charAt(c-1)}a+="@";d=b[2];d=h.trim(d);c=d.length;d=d.charAt(0);for(f=0;f<c-1;f++)d+="*";return a+d+b[3]}b=h.trim(a);a=b.length;if(!(4>=a)){c="";for(d=0;d<a-4;d++)c+="*";b=c+b.substr(a-
4,a-1)}return b}function c(){0===h(".cvf-account-switcher-check-mark:visible").length&&(h(".cvf-account-switcher-check-mark-area").remove(),h(".cvf-account-switcher-profile-details").toggleClass("cvf-account-switcher-profile-details cvf-account-switcher-profile-details-after-account-removed"))}function f(c){var d=new URLSearchParams(window.location.search);d.delete("switch_to_cid");d.has("errorCodes")||d.append("errorCodes","ACCOUNT_SWITCH_FAILED");b.addMetricCount(c);a.trigger(r.error,"automaticAccountSwitchFailure");
window.location.search=d}function p(){if(0!==h(".cvf-switch-to-cid").length)try{b.startMetricTimer(n.latency);var c=h(".cvf-switch-to-cid")[0].getAttribute("value");h(".cvf-automatic-switch-"+c)[0].click();setTimeout(function(){f(n.failureTimeout)},7E3);a.trigger(r.success,"automaticAccountSwitchSuccess");return!0}catch(t){f(n.failureClicking)}finally{b.endMetricTimer(n.latency)}return!1}var h=a.$,r={success:"cvf:account_switcher:success",error:"cvf:account_switcher:error"},n={latency:"AutomaticAccountSwitch_Latency",
failureClicking:"AutomaticAccountSwitch_FailureClicking",failureTimeout:"AutomaticAccountSwitch_FailureTimeout"};(function(){var a=h("#ap-account-switcher-container")[0],b=window.MutationObserver||window.WebKitMutationObserver;if(void 0!==a&&void 0!==b){var d=new b(function(a){for(var b=0;b<a.length;b++)if(null!==a[b].addedNodes){p()||c();d.disconnect();break}});d.observe(a,{attributes:!0,childList:!0,characterData:!0,subtree:!0})}})();(function(){h(".cvf-account-switcher-sign-out-link").live("click",
function(b){m(b,function(f){if(f.redirectUrl)window.location=f.redirectUrl,a.trigger("cvf:account_switcher","redirectOnSignOut");else if(f.succeeded){var g="."+h(b.target).attr("class").match(/cvf-account-switcher-account-group-\w+/g)[0];h(g+"-hide").hide();h(g+"-name").text(h("#cvf-account-switcher-sign-out-replace-text").text());h(g+"-claim").text(d(h(g+"-claim").text()));h(g+"-image").replaceWith(h("\x3cdiv /\x3e").append(h("#cvf-account-switcher-sign-out-replace-image").clone().removeClass("cvf-hidden")).html());
h(g+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher");f=f.switchedAccountId;void 0!==f&&h(".cvf-account-switcher-account-group-"+f+"-check-mark").show();c();window.location.reload()}else a.trigger(r.error,f)})})})();return{automaticAccountSwitch:p}});"use strict";
P.when("A","cvfInputValidatorConfig","ready").register("cvfInputValidator",function(a,l){return{getValidationResult:function(b){var m=!0,g=[],e=[];l.forEach(function(d){var c=a.$(d.invalidFieldAlertSelector),f=a.$(d.emptyFieldAlertSelector);d=b.find(d.inputSelector);d[0].required&&!d.val().trim()?(m=!1,0<f.length?(g.push(f),0<c.length&&e.push(c)):0<c.length&&g.push(c)):(0<f.length&&e.push(f),f=d[0].checkValidity&&!d[0].checkValidity(),m=m&&!f,c.length&&(f?g.push(c):e.push(c)))});return{isValid:m,
activeAlerts:g,inactiveAlerts:e}}}});"use strict";P.when("A","ready").register("cvfInputValidatorConfig",function(a){return[{inputSelector:".cvf-widget-input-code",invalidFieldAlertSelector:".cvf-widget-invalid-code-alert",emptyFieldAlertSelector:".cvf-widget-empty-field-alert"}]});P.register("a-sheet-wrapper",function(){return null});"use strict";
P.when("A","cvfFormDataGenerator","ready").register("cvfCaptcha",function(a,l){a=a.$;0===a(".cvf-widget-input-captcha").children("input").length?(a(".cvf-widget-input-captcha").attr("autocapitalize","off"),a(".cvf-widget-input-captcha").attr("autocorrect","off")):(a(".cvf-widget-input-captcha").children("input").attr("autocapitalize","off"),a(".cvf-widget-input-captcha").children("input").attr("autocorrect","off"))});"use strict";
P.when("A").register("cvf-client-side-counters-util",function(a){function l(a,m){var b=window.ue;b&&"function"===typeof b.count&&(m||(m=(b.count(a)||0)+1),b.count(a,m))}return{incrementCounter:function(a){l(a)},insertCounter:l,addMetricCount:function(a){window.ue&&"function"===typeof window.ue.count&&window.ue.count(a,1)},startMetricTimer:function(a){window.uet&&"function"===typeof window.uet&&window.uet("bb",a,{wb:1})},endMetricTimer:function(a){window.uex&&"function"===typeof window.uex&&window.uex("ld",
a,{wb:1})}}});
P.when("A","3p-promise","a-alert","codeResendTimer","cvf-client-side-counters-util","sms-retriever-handler","ready").execute("client-sms-request-controller",function(a,l,b,m,g,e){function d(){a.show("#cvf-otp-autoread-progress");g.incrementCounter(u.SHOW_AUTOREAD_WIDGET);var b=c();x.delegate("#cvf-input-code","input",function(){clearTimeout(b);a.hide("#cvf-otp-autoread-progress");var c=n("#cvf-auto-read-status");c.val()!==t.AUTOREAD_TIMEOUT&&c.val()!==t.AUTOREAD_SUCCESS&&(g.incrementCounter(u.CANCEL_AUTOREAD_WIDGET),c.val(t.AUTOREAD_CANCELLED))})}
function c(){return setTimeout(function(){var c=n("#cvf-auto-read-status");a.hide("#cvf-otp-autoread-progress");g.incrementCounter(u.AUTOREAD_WIDGET_TIMEOUT);c.val(t.AUTOREAD_TIMEOUT);b("#cvf-otp-autoread-timeout").show()},3E4)}function f(b){y=b;b=n("#cvf-auto-read-status");k&&b.val()!==t.AUTOREAD_TIMEOUT&&b.val()!==t.AUTOREAD_CANCELLED&&(b=y,n("#cvf-auto-read-status").val(t.AUTOREAD_SUCCESS),n("#cvf-input-code").val(b).trigger("input"),a.show("#cvf-otp-autoread-success"),x.submit())}function p(a){m.createTimer(Number(a.timeRemaining),
n("#resend-timer-message-id").val(),n("#resend-timer-complete-id").val().replace(/"/g,""),"timer","timer",!1);a=n("#wait-resend-auto-read");a.submit(function(a){a.preventDefault()});n(".wait-one-minute-continue").click(function(){z.location.reload()});a.removeClass("aok-hidden");x.addClass("aok-hidden")}function h(){b("#otp-request-failed-alert").show();n("#cvf-input-code").attr("disabled","disabled").addClass("a-form-disabled");n("#cvf-submit-otp-button").addClass("a-button-disabled");n("#cvf-resend-link").unbind().click(function(){z.location.reload()})}
function r(b){a.get(b,{success:function(a){a.wait?(g.incrementCounter(u.WAIT_RESEND),p(a)):a.redirect?(g.incrementCounter(u.REDIRECT),z.location.replace(a.redirect)):(a=a.smsFormat)?(g.incrementCounter(u.RECEIVED_FORMAT+":"+a),"androidAutoReadSmsWithAppHash"===a&&(k=!0,d(),y&&f(y))):(g.incrementCounter(u.FORMAT_NOT_RECEIVED),console.error("Failed to receive sms format"))},error:function(a,b,c){g.incrementCounter(u.AJAX_SMS_REQUEST_FAILED+":"+c);h();console.error("Ajax request failed",c)}})}var n=
a.$,z=this;e=[e];var t=Object.freeze({AUTOREAD_SUCCESS:"autoreadWidgetSuccess",AUTOREAD_CANCELLED:"autoreadWidgetCancelled",AUTOREAD_TIMEOUT:"autoreadWidgetTimeout"}),u=Object.freeze({SHOW_AUTOREAD_WIDGET:"OTPAutoReadShowWidget",CANCEL_AUTOREAD_WIDGET:"OTPAutoReadCanceWidgetForManualInput",AUTOREAD_WIDGET_TIMEOUT:"OTPAutoReadWidgetTimeout",RECEIVED_FORMAT:"OTPAutoReadReceivedFormat",FORMAT_NOT_RECEIVED:"OTPAutoReadFormatNotReceived",REDIRECT:"OTPAutoReadClientRedirect",AJAX_SMS_REQUEST_FAILED:"OTPAutoReadAjaxSmsRequestFailed",
WAIT_RESEND:"OTPAutoReadWaitResend"}),w=a.state("autoReadAttrs");if(w&&w.isClientDrivenOtpSendingEnabled){var A=w.arbParam;if(A){var x=n("#verification-code-form");if(0!==x.length){var y=null,k=!1;a.capabilities.android?(e=e.map(function(a){return a.isEnabled().then(function(b){return b?a.registerListener(f).then(function(a){return a}):{}})}),l.all(e).then(function(a){var b=[],c={};a.forEach(function(a){a.handlerCapability&&b.push(a.handlerCapability);a.handlerQueryParams&&n.extend(c,a.handlerQueryParams)});
a={arb:A,mode:"page_ajax",sendClientDrivenOtp:!0,capabilities:b.join()};n.extend(a,c);a=z.location.origin+"/ap/cvf/request?"+n.param(a);r(a)})):(l=z.location.origin+"/ap/cvf/request?"+n.param({arb:A,mode:"page_ajax",sendClientDrivenOtp:!0}),r(l))}}}});"use strict";
P.when("A","ready").register("codeResendTimer",function(a){function l(m,g,e,d,c,f){var l=(new Date).getTime();f&&(clearInterval(b),window.localStorage.removeItem("icaCVFTimeId"));b=setInterval(function(){var h=(new Date).getTime()-l,r=m-h;f&&window.localStorage.setItem("icaCVFTimeId",r);0>=r?(clearInterval(b),f&&window.localStorage.removeItem("icaCVFTimeId"),f?(a.$("#"+d).hide(),a.$("#"+c).show()):a.$("#"+c).html(e)):(h=g.split(" +timeleft+ "),f?(r=(new Date(r)).toISOString().slice(14,19),h=h[0].split('"').join("")+
r+h[1].split('"').join("")):h=h[0].split('"').join("")+Math.floor(r/1E3)+h[1].split('"').join(""),a.$("#"+d).html(h))},100)}var b;return{createTimer:function(a,b,e,d,c,f){return new l(a,b,e,d,c,f)},showTimer:function(){a.$("#cvf-resend-link").hide();a.$("#cvf-resend-text").removeClass("cvf-hidden")}}});"use strict";
P.when("A","cvfFormDataGenerator","ready").execute(function(a,l){var b=a.$;b(".cvf-widget-btn-val").click(function(a){var g=b(a.target).closest(".cvf-widget-form");a=l.getNameValue(b(a.target));g.append('\x3cinput type\x3d"hidden" name\x3d"'+a.name+'" value\x3d"'+a.value+'"\x3e').submit()})});"use strict";
P.when("A","cvfVersion","cvfFormDataGenerator","cvfInputValidator","ready").register("cvf",function(a,l,b,m){function g(g){function h(b){"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uex("ld",k.options.widgetMetricsScope,{wb:1});k.options.spinnerTarget&&k.options.spinnerTarget.hide();if(b.hasOwnProperty("error"))a.trigger(v.error,b.error);else if(b.redirectUrl)window.location=b.redirectUrl;else if(b.redirect){a.trigger(v.success,b.token,b.status,b.redirect);
if(k.options.showICALoadingAnimationOnSuccess){var c=d("#in-context-auth-loading-animation").prop("outerHTML");q.html(c)}k.options.autoDestroy?k.destroy():(d(".cvf-widget-alert").hide(),b.status?d(".cvf-widget-status-success").show():d(".cvf-widget-status-error").show(),y());a.trigger("cvf:verification:complete",b.status);q.find(".cvf-widget-btn").unbind("click",e);q.find(".cvf-widget-btn-val").unbind("click",e);a.off(v.success);a.off(v.error);a.off(v.content)}else q.html(b.replace(/<form/g,"\x3cdiv").replace(/<\/form/g,
"\x3c/div")),c=d(".cvf-widget-form-keep").clone().empty(),b=d(".cvf-widget-form-keep").children().clone(!0,!0),c=(new String(c.prop("outerHTML"))).replace(/<div/g,"\x3cform").replace(/<\/div/g,"\x3c/form"),d(".cvf-widget-form-keep").replaceWith(c),d(".cvf-widget-form-keep").html(b),w(),a.trigger(v.content)}function e(c,f,e){c.preventDefault();d(".cvf-widget-alert").hide();k.options.spinnerTarget&&k.options.spinnerTarget.show();var g=b.retrieveFormData(c.target,e);if(p()){if(k.options.showICAClaimUIOnClickChangeLink){k.options.showICAClaimUIOnClickChangeLink=
!1;k.options.spinnerTarget&&k.options.spinnerTarget.hide();c=d("#change-signin-claim-link-id").val();a.ajax(c,{method:"GET",dataType:"html",success:function(b){a.trigger("in-context-auth-content-update-event",b)},error:function(){d("#cvf-change-contact-link").hide();console.error("AJAX request to /ax/claim/ica failed.",this.error)}});return}if(e)q.find(".cvf-widget-input").removeClass("cvf-widget-input-error");else if(e=m.getValidationResult(g.form),e.inactiveAlerts.forEach(function(a){a.hide()}),
e.activeAlerts.forEach(function(a){a.show()}),e.isValid)q.find(".cvf-widget-input").removeClass("cvf-widget-input-error");else{k.options.spinnerTarget&&k.options.spinnerTarget.hide();q.find(".cvf-widget-input").addClass("cvf-widget-input-error");t();u();return}}e=g.inputData.serializeArray();f&&e.push(b.getNameValue(c.target));a.ajax(B+g.requestPath,{method:"POST",params:e,success:h,error:x})}function n(a){13===a.keyCode&&e(a)}function p(){return 0<q.find('input[name\x3d"is_in_context_auth"]').length}
function t(){q.find('input[name\x3d"code"]').focus()}function u(){q.find('input[name\x3d"code"]').keypress(n)}function w(){q.find(".cvf-widget-btn").click(function(a){e(a,!1)});q.find(".cvf-widget-btn-val").click(function(a){e(a,!0)});p()||t();u();q.find(".cvf-widget-v2-link-resend").click(function(a){e(a,!1,!0)});q.find("#cvf-signin-with-password").click(function(a){a.preventDefault();q.find("#cvf-signin-with-password-instead-form").submit()});q.find(".cvf-widget-v2-change-contact-link").click(function(a){k.options.showICAClaimUIOnClickChangeLink=
!0;e(a,!1)})}function A(b){return function(c,d,f){"timeout"!==d||3<=C?a.trigger(v.error,f):a.delay(b,10*C++)}}function x(b,c,d){k.options.spinnerTarget&&k.options.spinnerTarget.hide();a.trigger(v.error,d)}function y(){d.each(q.find("input"),function(a,b){a=d(b);a.attr("disabled","disabled");a.hasClass("a-input-text")?a.addClass("a-form-disabled"):a.hasClass("a-button-input")?a.closest(".a-button").addClass("a-button-disabled"):a.closest(".a-input-text-wrapper").length&&a.closest(".a-input-text-wrapper").addClass("a-form-disabled")});
d.each(q.find("a"),function(a,b){a=d(b);a.hasClass("cvf-widget-link-disable-target")&&a.addClass("cvf-link-disabled")})}var k=this;f++;var v={success:"cvf:"+f+":success",error:"cvf:"+f+":error",content:"cvf:"+f+":content"};k.options={};d.extend(k.options,c,g);(function(a){if(1!==d(a.target).length)throw Error("The CVF widget requires a unique element.");if(!d.isFunction(a.onSuccess))throw Error("The CVF widget requires a success callback function.");if(!d.isFunction(a.onError))throw Error("The CVF widget requires an error callback function.");
})(k.options);var B=k.options.server,q=d(k.options.target);a.on(v.success,k.options.onSuccess);a.on(v.error,k.options.onError);a.on(v.content,k.options.onContent);k.start=function(){var b=B+"/ap/cvf/request.embed",c=k.options.requestToken,f=k.options.requestArbToken,e=k.options.associationHandle,g=k.options.language,n=0===d.trim(c).length,m=0===d.trim(f).length;if(n&&m)throw Error("The CVF widget requires a request token or arb token.");n=0!==d.trim(e).length;var r=0!==d.trim(g).length,p={};m?p.requestToken=
c:p.arb=f;p.CVFVersion=l.version;p.AUIVersion=P.AUI_BUILD_DATE;r&&(p.language=g);n&&(p["openid.assoc_handle"]=e);"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uet("bb",k.options.widgetMetricsScope,{wb:1});a.ajax(b,{method:"GET",params:p,success:h,error:A(k.start)})};k.destroy=function(){q.html("")};w();var C=0;k.options.autoStart&&k.start()}function e(a){return new g(a)}var d=a.$,c={server:"",target:void 0,requestToken:void 0,requestArbToken:void 0,onSuccess:void 0,
onError:void 0,onContent:function(){},spinnerTarget:void 0,autoStart:!0,autoDestroy:!0,widgetMetricsScope:void 0,associationHandle:void 0,language:void 0,showICALoadingAnimationOnSuccess:!1,showICAClaimUIOnClickChangeLink:!1},f=0;a.on("cvf:verification:request",function(b){var c=d("#"+b),f=c.data("token"),g=c.data("spinnerId");g=d("#"+g);e({target:c,spinnerTarget:g,requestToken:f,onSuccess:function(c,d,f){a.trigger("cvf:verification:complete:"+b,c,d,f)},onError:function(c){a.trigger("cvf:verification:error:"+
b,c)},autoStart:!0,autoDestroy:!1})});return{create:e}});"use strict";
P.when("A","ready").register("cvfFormDataGenerator",function(a){var l=a.$;return{retrieveFormData:function(a,m){a=l(a).closest(".cvf-widget-form");m&&(a=l(".cvf-widget-form-resend"));return{requestPath:a.data("use-only-form-action")?a.attr("action"):"/ap/cvf/"+a.attr("action")+".embed",inputData:a.find(".cvf-widget-input,.cvf-widget-hidden-fields,.cvf-widget-input :input"),form:a}},getNameValue:function(a){a=l(a);var b=a.attr("name");b||(b=a.closest(".cvf-widget-btn-val").attr("data-name"));var g=
a.attr("value");g||(g=a.closest(".cvf-widget-btn-val").attr("data-value"));return{name:b,value:g}}}});"use strict";
P.when("A","cvf","ready").execute(function(a,l){var b=a.$;b(document).ready(function(){function a(a,b,c){window.location=c;console.log("Client Side: "+a)}function g(a){console.log(a)}var e=b(".cvf-widget-spinner"),d=b("#cvf-widget-content");if(1===d.length){var c=b('[name\x3d"requestToken"]').first().attr("value");l.create({target:d,spinnerTarget:e,requestToken:c,onSuccess:a,onError:g,autoStart:!1})}})});"use strict";
P.when("A","ready").register("phoneFormField",function(a){function l(){a:{for(var a=b("select[name\x3d'cvf_phone_cc']").val()||"",e=0;e<m.length;e++){var d=m[e];if(a.toUpperCase()===d){b("#mobileClaimDisclosureMessage").removeClass("a-hidden aok-hidden").show();b("#mobileClaimDisclosureMessageRelaxed").addClass("aok-hidden").hide();break a}}b("#mobileClaimDisclosureMessageRelaxed").removeClass("a-hidden aok-hidden").show();b("#mobileClaimDisclosureMessage").addClass("aok-hidden").hide()}}var b=a.$,
m=["US","CA","FR"];0<b("select[name\x3d'cvf_phone_cc']").length&&0<b("#mobileClaimDisclosureMessage").length&&0<b("#mobileClaimDisclosureMessageRelaxed").length&&(l(),b("select[name\x3d'cvf_phone_cc']").change(l))});"use strict";P.when("A").execute(function(a){a.declarative("auth-popup","click",function(a){var b=a.data;a=a.$target.closest("a")[0];(b=window.open(a.href,a.target,b.windowOptions))&&b.focus()})});
P.register("android-sms-otp-parser",function(){return{parseOtpCode:function(a){if(a&&(a=a.match(/(([\s\S]*[^0-9])|(^))([0-9]{4,6})[^0-9][\s\S]*[a-zA-Z0-9+\\\/]{11}/)||[],0<a.length))return a[4]}}});
P.when("A","mobile-auth-platform","3p-promise","android-sms-otp-parser","cvf-client-side-counters-util","ready").register("sms-retriever-handler",function(a,l,b,m,g){function e(a){(f=a.isSupported)?g.incrementCounter(c.ENABLED):g.incrementCounter(c.DISABLED);p={appHash:a.appHash}}function d(){return new b(function(a){p?a(p):l.isSmsRetrieverEnabled(function(b){e(b);a(p)})})}var c=Object.freeze({ENABLED:"SmsRetrieverEnabled",DISABLED:"SmsRetrieverDisabled",SMS_LISTENER_FAILED:"SmsRetrieverListenerFailedToRegister",
RECEIVED_INVALID_SMS:"SmsRetrieverListenerReceivedInvalidSms",RECEIVED_VALID_SMS:"SmsRetrieverListenerReceivedValidSms"}),f=null,p=null;return{isEnabled:function(){return new b(function(a){null!==f?a(f):l.isSmsRetrieverEnabled(function(b){e(b);a(f)})})},registerListener:function(a){return new b(function(b){l.registerMAPSmsReceiver(function(b){b.isRegistered?(b=m.parseOtpCode(b.sms))?(g.incrementCounter(c.RECEIVED_VALID_SMS),a(b)):g.incrementCounter(c.RECEIVED_INVALID_SMS):g.incrementCounter(c.SMS_LISTENER_FAILED)});
d().then(function(a){f?b({handlerCapability:"smsRetriever",handlerQueryParams:a}):b({})})})}}});"use strict";
P.when("A","a-spinner","ready").execute(function(a,l){function b(){e(".otp-input-box").attr("disabled","disabled");e("input[name\x3d'code']").val(m());(null!==e(".otp-input-box-container").data("isembed")?e(".otp-input-box-container").data("isembed"):1)?e(".cvf-widget-btn-verify").click():(a.capabilities.isAmazonApp||l("#otp-input-spinner").show(),e("#verification-code-form").submit())}function m(){var a="";e("input[name^\x3dotc]").each(function(b){a+=e(this).val()});return a}function g(){e(".cvf-widget-alert").is(":visible")&&
(e(".otp-input-box").removeClass("otp-input-box-alert"),e(".cvf-widget-alert").hide())}var e=a.$,d=/^\d+$/;a.declarative("otp-inputbox-handler","focusin",function(a){a=a.$target;a.is(".otp-input-box")&&(a.attr("name").match("otc-1")||""===a.prev().val()&&a.prev().focus())});a.declarative("otp-inputbox-handler","keyup",function(a){var c=a.$event;a=a.$target;a.is(".otp-input-box")&&(c=c.which||c.keyCode,-1===[16,9,224,18,17].indexOf(c))&&(-1!==[8,37,46].indexOf(c)?a.prev()&&!a.attr("name").match("otc-1")&&
(a.val(""),a.prev().select()):d.test(a.val())?a.attr("name").match("otc-6")?b():a.next()&&(g(),a.next().select()):a.val(""))});e(".otp-input-box").live("input",function(a){a=e(a.target);var c=a.val();g();if(1!==c.length)for(var d=0;d<c.length;d++){a.val(c.charAt(d));if(a.attr("name").match("otc-6")){b();break}a=a.next();a.focus()}});a.declarative("otp-inputbox-handler","click",function(){e("input[name^\x3dotc]").each(function(a){""===e(this).val()&&e(this).focus()})})});